// ═══════════════════════════════════════════════════════════════
// catalogSeed.js — v10.G
// ─────────────────────────────────────────────────────────────
// SEED initial du catalogue d'articles EPJ.
//
// IMPORTANT : ce fichier est utilisé UNIQUEMENT lors de l'opération
// '🔄 Réinitialiser Firebase' dans l'écran Admin Catalogue.
// En fonctionnement normal, l'app charge la collection 'catalogue'
// depuis Firestore via onSnapshot, et n'utilise jamais ce seed.
//
// Source : BASE_Catalogue_APP_EPJ.xlsx fourni par Pierre-Julien
// le 7 mai 2026, après nettoyage et complétion des fournisseurs.
//
// Format de chaque article :
//   c            : catégorie (ex: 'Béton + Descente')
//   s            : sous-catégorie (ex: 'Capri')
//   r            : référence — clé unique (ex: 'CAP 959922')
//   n            : désignation lisible (ex: 'BOITE MAXIBANCHE GTI IRL2')
//   u            : unité (ex: 'Pièce', 'ML')
//   stock        : booléen (true = tenu en stock interne)
//   fournisseur  : nom lisible du fournisseur principal (v10.G)
//   codeEsabora  : code court Esabora 3-4 lettres (v10.G)
//   img          : URL de photo (optionnel)
//
// Stats : 583 articles, 16 catégories, 107 sous-catégories.
// 582/583 articles ont fournisseur+codeEsabora pré-remplis.
//
// v10.G+1 : ce fichier sera SUPPRIMÉ une fois Firestore peuplé en prod
// chez tous les utilisateurs. Le bouton Réinitialiser proposera alors
// d'importer un Excel à la place.
// ═══════════════════════════════════════════════════════════════

export const CATALOG_SEED = [
  {c:"Béton + Descente",s:"Capri",r:"CAP 959922",n:"BOITE MAXIBANCHE GTI IRL2",u:"Pièce",stock:false,fournisseur:"SONEPAR",codeEsabora:"SONE"},
  {c:"Béton + Descente",s:"Capri",r:"CAP 959937",n:"BOITE MAXIBANCHE DOS A DOS IRL",u:"Pièce",stock:false,fournisseur:"SONEPAR",codeEsabora:"SONE"},
  {c:"Béton + Descente",s:"Capri",r:"CAP 859320",n:"Boîtier 32 A Ø 80",u:"Pièce",stock:false,fournisseur:"SONEPAR",codeEsabora:"SONE"},
  {c:"Béton + Descente",s:"Capri",r:"CAP 598940",n:"CONE D'EXTRACTION",u:"Pièce",stock:false,fournisseur:"SONEPAR",codeEsabora:"SONE"},
  {c:"Béton + Descente",s:"Rallonge Doublage",r:"SIB P0106009",n:"Manchon doublage",u:"Pièce",stock:false,fournisseur:"SONEPAR",codeEsabora:"SONE"},
  {c:"Béton + Descente",s:"Rallonge Doublage",r:"SIB P0106108",n:"Anneau adaptateur appareil vis",u:"Pièce",stock:false,fournisseur:"SONEPAR",codeEsabora:"SONE"},
  {c:"Béton + Descente",s:"Sib",r:"SIB P01052",n:"ANNEAU A VIS UNIVERSEL",u:"Pièce",stock:false,fournisseur:"SONEPAR",codeEsabora:"SONE"},
  {c:"Béton + Descente",s:"Sib",r:"SIB P0110013",n:"BOITIER + COUVERCLE 32 AMPERES",u:"Pièce",stock:false,fournisseur:"SONEPAR",codeEsabora:"SONE"},
  {c:"Béton + Descente",s:"Blm",r:"BLI 779930",n:"BANCHEBOX IRL25 murs de 160 à 200 mm",u:"Pièce",stock:false,fournisseur:"SONEPAR",codeEsabora:"SONE"},
  {c:"Béton + Descente",s:"Blm",r:"BLI 779925",n:"BANCHEBOX IRL25 murs de 160 à 200 mm (non percée)",u:"Pièce",stock:false,fournisseur:"SONEPAR",codeEsabora:"SONE"},
  {c:"Béton + Descente",s:"Blm",r:"BLI 759010",n:"COUV. DE POSE MURBOX",u:"Pièce",stock:false,fournisseur:"SONEPAR",codeEsabora:"SONE"},
  {c:"Béton + Descente",s:"Blm",r:"BLI 759920",n:"BAGUE DE RALLONGUE MURBOX 20MM",u:"Pièce",stock:false,fournisseur:"SONEPAR",codeEsabora:"SONE"},
  {c:"Béton + Descente",s:"Blm",r:"BLI 750090",n:"DISTANCIER MURBOX TYPE 'C' 71X100 MM",u:"Pièce",stock:false,fournisseur:"SONEPAR",codeEsabora:"SONE"},
  {c:"Béton + Descente",s:"Blm",r:"BLI 759020",n:"ANNEAU A VIS MURBOX",u:"Pièce",stock:false,fournisseur:"SONEPAR",codeEsabora:"SONE"},
  {c:"Béton + Descente",s:"Blm",r:"BLI 755108",n:"AIMANT RESINE 800N JAUNE",u:"Pièce",stock:false,fournisseur:"SONEPAR",codeEsabora:"SONE"},
  {c:"Béton + Descente",s:"Tube Iro",r:"GEW DX27725",n:"IRL 3321 D25 T G TUBE IRL (GEWISS)",u:"Pièce",stock:true,fournisseur:"SONEPAR",codeEsabora:"SONE"},
  {c:"Béton + Descente",s:"Tube Iro",r:"IBO B28970",n:"IRL 3321 D25 T G TUBE IRL",u:"Pièce",stock:false,fournisseur:"SONEPAR",codeEsabora:"SONE"},
  {c:"Béton + Descente",s:"Tube Iro",r:"IBO B28980",n:"IRL 3321 D32 T G TUBE IRL",u:"Pièce",stock:false,fournisseur:"SONEPAR",codeEsabora:"SONE"},
  {c:"Béton + Descente",s:"Terre",r:"FIL CUIVRENU25C50",n:"CUIVRE NU 1X25²  50M",u:"Pièce",stock:false,fournisseur:"SONEPAR",codeEsabora:"SONE"},
  {c:"Béton + Descente",s:"Terre",r:"KKE RG10-50",n:"RACCORD A GRIFFES 10 A 50MM",u:"Pièce",stock:false,fournisseur:"SONEPAR",codeEsabora:"SONE"},
  {c:"Béton + Descente",s:"Terre",r:"CAT AMG-10",n:"PIQUET AC/GALVA D.16MMX1,00M",u:"Pièce",stock:false,fournisseur:"SONEPAR",codeEsabora:"SONE"},
  {c:"Conduit + Manchon",s:"Icta",r:"EFI ECICTA20T",n:"FLEX ICTA 3422 AVEC FIL 20MM",u:"Pièce",stock:true,fournisseur:"ELECTRO FRANCE INTERNET",codeEsabora:"EFI"},
  {c:"Conduit + Manchon",s:"Icta",r:"EFI ECICTA25T",n:"FLEX ICTA 3422 AVEC FIL 25MM",u:"Pièce",stock:true,fournisseur:"ELECTRO FRANCE INTERNET",codeEsabora:"EFI"},
  {c:"Conduit + Manchon",s:"Icta",r:"EFI ECICTA32T",n:"FLEX ICTA 3422 AVEC FIL 32MM",u:"Pièce",stock:true,fournisseur:"ELECTRO FRANCE INTERNET",codeEsabora:"EFI"},
  {c:"Conduit + Manchon",s:"Icta",r:"EFI ECICTA40T",n:"FLEX ICTA 3422 AVEC FIL 40MM",u:"Pièce",stock:true,fournisseur:"ELECTRO FRANCE INTERNET",codeEsabora:"EFI"},
  {c:"Conduit + Manchon",s:"Manchon",r:"SIB P0300209",n:"MANCHON ICT 20",u:"Pièce",stock:false,fournisseur:"SONEPAR",codeEsabora:"SONE"},
  {c:"Conduit + Manchon",s:"Manchon",r:"SIB P0300254",n:"MANCHON ICT 25",u:"Pièce",stock:false,fournisseur:"SONEPAR",codeEsabora:"SONE"},
  {c:"Conduit + Manchon",s:"Manchon",r:"SIB P0300322",n:"MANCHON ICT 32",u:"Pièce",stock:false,fournisseur:"SONEPAR",codeEsabora:"SONE"},
  {c:"Conduit + Manchon",s:"Manchon",r:"SIB P0300400",n:"MANCHON ICT 40",u:"Pièce",stock:false,fournisseur:"SONEPAR",codeEsabora:"SONE"},
  {c:"Conduit + Manchon",s:"Janolene Rouge",r:"PUM 55148",n:"COURONNE GAINE TPC 450N ROUGE 50M D 40",u:"Pièce",stock:false,fournisseur:"PUM",codeEsabora:"PUM"},
  {c:"Conduit + Manchon",s:"Janolene Rouge",r:"PUM 55142",n:"COURONNE GAINE TPC 450N ROUGE 25M D 63",u:"Pièce",stock:false,fournisseur:"PUM",codeEsabora:"PUM"},
  {c:"Conduit + Manchon",s:"Janolene Rouge",r:"PUM 55144",n:"COURONNE GAINE TPC 450N ROUGE 25M D 90",u:"Pièce",stock:false,fournisseur:"PUM",codeEsabora:"PUM"},
  {c:"Conduit + Manchon",s:"Janolene Rouge",r:"PUM 55145",n:"COURONNE GAINE TPC 450N ROUGE 25M D 110",u:"Pièce",stock:false,fournisseur:"PUM",codeEsabora:"PUM"},
  {c:"Conduit + Manchon",s:"Janolene Rouge",r:"PUM 55147",n:"COURONNE GAINE TPC 450N ROUGE 25M D 160",u:"Pièce",stock:false,fournisseur:"PUM",codeEsabora:"PUM"},
  {c:"Conduit + Manchon",s:"Janolene Ik10",r:"CNT 12024320",n:"RLX ICTA 3522 IK10 25M AV.TIRE FIL D63",u:"Pièce",stock:false,fournisseur:"SONEPAR",codeEsabora:"SONE"},
  {c:"Conduit + Manchon",s:"Janolene Ik10",r:"CNT 12025120",n:"RLX ICTA 3522 IK10 25M AV.TIRE FIL D90",u:"Pièce",stock:false,fournisseur:"SONEPAR",codeEsabora:"SONE"},
  {c:"Conduit + Manchon",s:"Janolene Ik10",r:"CNT 12025520",n:"RLX ICTA 3522 IK10 25M AV.TIRE FIL D110",u:"Pièce",stock:false,fournisseur:"SONEPAR",codeEsabora:"SONE"},
  {c:"Conduit + Manchon",s:"Janolene Ik10",r:"PUM 64998",n:"RLX ICTA 3522 IK10 25M AV.TIRE FIL D160",u:"Pièce",stock:false,fournisseur:"PUM",codeEsabora:"PUM"},
  {c:"Conduit + Manchon",s:"Pvc Ft",r:"PUM 12867",n:"GAINE PVC LST 6M 45X1,8",u:"Pièce",stock:false,fournisseur:"PUM",codeEsabora:"PUM"},
  {c:"Conduit + Manchon",s:"Pvc Ft",r:"PUM 56220",n:"COURBE TELECOM MF-90' R210 D 45",u:"Pièce",stock:false,fournisseur:"PUM",codeEsabora:"PUM"},
  {c:"Conduit + Manchon",s:"Pvc Ft",r:"PUM 7600",n:"COURBE TELECOM MF-45' R525 D 45",u:"Pièce",stock:false,fournisseur:"PUM",codeEsabora:"PUM"},
  {c:"Conduit + Manchon",s:"Tube Iro",r:"IBO B28960",n:"Tube iro - PVC - tulipé - Ø20 mm - long 3 m - Gris",u:"Pièce",stock:false,fournisseur:"SONEPAR",codeEsabora:"SONE"},
  {c:"Conduit + Manchon",s:"Tube Iro",r:"IBO B28970",n:"Tube iro - PVC - tulipé - Ø25 mm - long 3 m - Gris",u:"Pièce",stock:false,fournisseur:"SONEPAR",codeEsabora:"SONE"},
  {c:"Conduit + Manchon",s:"Tube Iro",r:"IBO B28990",n:"Tube iro - PVC - tulipé - Ø40 mm",u:"Pièce",stock:false,fournisseur:"SONEPAR",codeEsabora:"SONE"},
  {c:"Conduit + Manchon",s:"Tube Iro",r:"IBO B29010",n:"Tube iro - PVC - tulipé - Ø63 mm",u:"Pièce",stock:false,fournisseur:"SONEPAR",codeEsabora:"SONE"},
  {c:"Équip. Sous-Sol",s:"Tableautin",r:"GW42001",n:"TABLEAUTIN 200X150X40 IP41 (BS)",u:"Pièce",stock:false,fournisseur:"SONEPAR",codeEsabora:"SONE"},
  {c:"Équip. Sous-Sol",s:"Tableautin",r:"MIH R152",n:"TABLEAU BOIS (BS)",u:"Pièce",stock:false,fournisseur:"SONEPAR",codeEsabora:"SONE"},
  {c:"Équip. Sous-Sol",s:"Tableautin",r:"MIH R150",n:"TABLEAU BOIS (DECT)",u:"Pièce",stock:false,fournisseur:"SONEPAR",codeEsabora:"SONE"},
  {c:"Équip. Sous-Sol",s:"Installation De Chantier",r:"BRE 1159961",n:"SOCLE 4 PRISES NOIR IP44 AVEC VOLETS (REGLETTE)",u:"Pièce",stock:true,fournisseur:"SONEPAR",codeEsabora:"SONE"},
  {c:"Équip. Sous-Sol",s:"Installation De Chantier",r:"DIG-31132",n:"Coffret de distribution 4 PC 2P+T + AU",u:"Pièce",stock:true,fournisseur:"SATAIR",codeEsabora:"SAT"},
  {c:"Équip. Sous-Sol",s:"Installation De Chantier",r:"DIG-31324",n:"Coffret de distribution 4PC Nf/1PC 3P+N+T 32A + AU",u:"Pièce",stock:true,fournisseur:"SATAIR",codeEsabora:"SAT"},
  {c:"Équip. Sous-Sol",s:"Installation De Chantier",r:"ARI 50416",n:"ECOLED BLC 5,5W/4000K (LAMPE CHANTIER)",u:"Pièce",stock:true,fournisseur:"SONEPAR",codeEsabora:"SONE"},
  {c:"Équip. Sous-Sol",s:"Luminaire",r:"RES 607000",n:"SIMPLY 35W 4000K 4196lm (FLUO COURT)",u:"Pièce",stock:true,fournisseur:"RESISTEX",codeEsabora:"RES"},
  {c:"Équip. Sous-Sol",s:"Luminaire",r:"RES 607001",n:"SIMPLY 50W 4000K 5517lm (FLUO LONG)",u:"Pièce",stock:true,fournisseur:"RESISTEX",codeEsabora:"RES"},
  {c:"Équip. Sous-Sol",s:"Luminaire",r:"RES 607011",n:"SIMPLY 50W 4000K 5517lm (FLUO LONG) + 1M50 de câble",u:"Pièce",stock:true,fournisseur:"RESISTEX",codeEsabora:"RES"},
  {c:"Équip. Sous-Sol",s:"Luminaire",r:"RES 830000",n:"HUBO 18W CCT 4000K 1678lm (LOCAUX ANNEXE)",u:"Pièce",stock:false,fournisseur:"RESISTEX",codeEsabora:"RES"},
  {c:"Équip. Sous-Sol",s:"Luminaire",r:"RES 830001",n:"HUBO 18W DET CCT 4000K 1678lm (LOCAUX ANNEXE)",u:"Pièce",stock:false,fournisseur:"RESISTEX",codeEsabora:"RES"},
  {c:"Équip. Sous-Sol",s:"Luminaire",r:"RES 830020",n:"HUBO 8/15W CCT 4000K 1678lm (LOCAUX ANNEXE)",u:"Pièce",stock:true,fournisseur:"RESISTEX",codeEsabora:"RES"},
  {c:"Équip. Sous-Sol",s:"Luminaire",r:"RES 830021",n:"HUBO 8/15W DET CCT 4000K 1678lm (LOCAUX ANNEXE)",u:"Pièce",stock:true,fournisseur:"RESISTEX",codeEsabora:"RES"},
  {c:"Équip. Sous-Sol",s:"Luminaire",r:"RES 830022",n:"HUBO 17/24W CCT 4000K 1678lm (LOCAUX ANNEXE)",u:"Pièce",stock:false,fournisseur:"RESISTEX",codeEsabora:"RES"},
  {c:"Équip. Sous-Sol",s:"Luminaire",r:"RES 830023",n:"HUBO 17/24W DET CCT 4000K 1678lm (LOCAUX ANNEXE)",u:"Pièce",stock:false,fournisseur:"RESISTEX",codeEsabora:"RES"},
  {c:"Équip. Sous-Sol",s:"Detecteur",r:"BE4 91101",n:"LC CLICK DETECTEUR 140DEG BLANC",u:"Pièce",stock:false,fournisseur:"SONEPAR",codeEsabora:"SONE"},
  {c:"Équip. Sous-Sol",s:"Detecteur",r:"BE4 91102",n:"LC CLICK DETECTEUR 200DEG BLANC",u:"Pièce",stock:false,fournisseur:"SONEPAR",codeEsabora:"SONE"},
  {c:"Équip. Sous-Sol",s:"Detecteur",r:"BE4 92194",n:"DETECTEUR PD3-1C-APPLIQUE 360°",u:"Pièce",stock:false,fournisseur:"SONEPAR",codeEsabora:"SONE"},
  {c:"Équip. Sous-Sol",s:"B.a.e.s.",r:"ZEM AGV-60-NM",n:"Grille de protection IK 10 pour bloc XENA FLAT",u:"Pièce",stock:false,fournisseur:"ZEMPER",codeEsabora:"ZEM"},
  {c:"Équip. Sous-Sol",s:"B.a.e.s.",r:"ZEM LXF-3045EX",n:"Bloc évacuation SATI 45 lms IP42/IK04 - 0,85w",u:"Pièce",stock:false,fournisseur:"ZEMPER",codeEsabora:"ZEM"},
  {c:"Équip. Sous-Sol",s:"Tube Iro",r:"SCH IMT35201",n:"(TUBE NOIR POUR BS) IRL X LOURD 4554 STD 20",u:"Pièce",stock:false,fournisseur:"SONEPAR",codeEsabora:"SONE"},
  {c:"Équip. Sous-Sol",s:"Tube Iro",r:"SCH IMT35213",n:"MANCHON Ø20 TUB.LOURD SS HALO",u:"Pièce",stock:true,fournisseur:"SONEPAR",codeEsabora:"SONE"},
  {c:"Équip. Sous-Sol",s:"Tube Iro",r:"IBO B28960",n:"Tube iro - PVC - tulipé - Ø20 mm - long 3 m - Gris",u:"Pièce",stock:false,fournisseur:"SONEPAR",codeEsabora:"SONE"},
  {c:"Équip. Sous-Sol",s:"Tube Iro",r:"IBO B28970",n:"Tube iro - PVC - tulipé - Ø25 mm - long 3 m - Gris",u:"Pièce",stock:false,fournisseur:"SONEPAR",codeEsabora:"SONE"},
  {c:"Équip. Sous-Sol",s:"Equipement Box Garage",r:"POI MM32LM",n:"Compteur monophasé 45A Certifié MID",u:"Pièce",stock:false,fournisseur:"POLIER",codeEsabora:"POLI"},
  {c:"Équip. Sous-Sol",s:"Equipement Box Garage",r:"ENI P01330740",n:"COMPTEUR MEMO MD32 230VAC 32A",u:"Pièce",stock:false,fournisseur:"SONEPAR",codeEsabora:"SONE"},
  {c:"Équip. Sous-Sol",s:"Equipement Box Garage",r:"BLD BL000047",n:"MILO-HUBLOT-1XE27-IK10-IP65 (ECL BOX)",u:"Pièce",stock:false,fournisseur:"BE LED",codeEsabora:"BLD"},
  {c:"Équip. Sous-Sol",s:"Equipement Box Garage",r:"RES 830251",n:"RESIDETECT INFRAROUGE 1XE27 BLANC (ECL BOX AVEC DET)",u:"Pièce",stock:false,fournisseur:"RESISTEX",codeEsabora:"RES"},
  {c:"Équip. Sous-Sol",s:"Equipement Box Garage",r:"BIY 80100038991",n:"ECOBASIC LED A60 E27 240V 10W",u:"Pièce",stock:false,fournisseur:"SONEPAR",codeEsabora:"SONE"},
  {c:"Plexo",s:"Boite Plexo",r:"BLI 560409",n:"BOITE PLEXO 100X100",u:"Pièce",stock:true,fournisseur:"SONEPAR",codeEsabora:"SONE"},
  {c:"Plexo",s:"Boite Plexo",r:"BLI 560209",n:"BOITE PLEXO Ø70",u:"Pièce",stock:true,fournisseur:"SONEPAR",codeEsabora:"SONE"},
  {c:"Plexo",s:"Boite Plexo",r:"BLI 560309",n:"BOITE PLEXO 80x80",u:"Pièce",stock:true,fournisseur:"SONEPAR",codeEsabora:"SONE"},
  {c:"Plexo",s:"Boite Plexo",r:"BLI 515509",n:"BOITE OPTIBOX IP55 1/4T 155X110X80",u:"Pièce",stock:false,fournisseur:"SONEPAR",codeEsabora:"SONE"},
  {c:"Plexo",s:"Boite Plexo",r:"BLI 515609",n:"BOITE PLEXO 175x150x80",u:"Pièce",stock:false,fournisseur:"SONEPAR",codeEsabora:"SONE"},
  {c:"Plexo",s:"Prise",r:"SCH MUR35031",n:"PRISE PLEXO EN SAILLIE GRIS",u:"Pièce",stock:false,fournisseur:"SONEPAR",codeEsabora:"SONE"},
  {c:"Plexo",s:"Prise",r:"SCH MUR39030",n:"PRISE PLEXO EN SAILLIE BLANC",u:"Pièce",stock:false,fournisseur:"SONEPAR",codeEsabora:"SONE"},
  {c:"Plexo",s:"Prise",r:"SCH MUR36010",n:"PRISE PLEXO IRVE EN SAILLIE GRIS",u:"Pièce",stock:false,fournisseur:"SONEPAR",codeEsabora:"SONE"},
  {c:"Plexo",s:"Prise",r:"SCH MUR39010",n:"PRISE PLEXO IRVE EN SAILLIE BLANC",u:"Pièce",stock:false,fournisseur:"SONEPAR",codeEsabora:"SONE"},
  {c:"Plexo",s:"Va Et Vient",r:"SCH MUR35021",n:"VA-ET-VIENT PLEXO SAILLI GRIS",u:"Pièce",stock:false,fournisseur:"SONEPAR",codeEsabora:"SONE"},
  {c:"Plexo",s:"Va Et Vient",r:"SCH MUR39021",n:"VA-ET-VIENT PLEXO SAILLI BLANC",u:"Pièce",stock:false,fournisseur:"SONEPAR",codeEsabora:"SONE"},
  {c:"Plexo",s:"Bp",r:"SCH MUR35026",n:"BP PLEXO EN SAILLIE GRIS",u:"Pièce",stock:false,fournisseur:"SONEPAR",codeEsabora:"SONE"},
  {c:"Plexo",s:"Bp",r:"SCH MUR39026",n:"BP PLEXO EN SAILLIE BLANC",u:"Pièce",stock:false,fournisseur:"SONEPAR",codeEsabora:"SONE"},
  {c:"Plexo",s:"Support Saillie",r:"SCH MUR37911",n:"SUPPORT 1 POSTE GRIS",u:"Pièce",stock:false,fournisseur:"SONEPAR",codeEsabora:"SONE"},
  {c:"Plexo",s:"Support Saillie",r:"SCH MUR39911",n:"SUPPORT 1 POSTE BLANC",u:"Pièce",stock:false,fournisseur:"SONEPAR",codeEsabora:"SONE"},
  {c:"Plexo",s:"Support Saillie",r:"SCH MUR37914",n:"SUPPORT 2 POSTE HORIZONTAL GRIS",u:"Pièce",stock:false,fournisseur:"SONEPAR",codeEsabora:"SONE"},
  {c:"Plexo",s:"Support Saillie",r:"SCH MUR39914",n:"SUPPORT 2 POSTE HORIZONTAL BLANC",u:"Pièce",stock:false,fournisseur:"SONEPAR",codeEsabora:"SONE"},
  {c:"Plexo",s:"Support Saillie",r:"SCH MUR37912",n:"SUPPORT 2 POSTE VERTICAL GRIS",u:"Pièce",stock:false,fournisseur:"SONEPAR",codeEsabora:"SONE"},
  {c:"Plexo",s:"Support Saillie",r:"SCH MUR39912",n:"SUPPORT 2 POSTE VERTICAL BLANC",u:"Pièce",stock:false,fournisseur:"SONEPAR",codeEsabora:"SONE"},
  {c:"Placo",s:"Simple",r:"BLI 613409",n:"LOT DE 300 BLUE BOX + SIMPLES + SCIE CLOCHE",u:"Pièce",stock:false,fournisseur:"SONEPAR",codeEsabora:"SONE"},
  {c:"Placo",s:"Simple",r:"BLI 675400",n:"LOT DE 500 NO AIR II + 1 SCIE CLOCHE",u:"Pièce",stock:false,fournisseur:"SONEPAR",codeEsabora:"SONE"},
  {c:"Placo",s:"Simple",r:"BLI 613409U",n:"BOITE PLACO BLUE BOX Ø68 SIMPLE UNITAIRE",u:"Pièce",stock:true,fournisseur:"SONEPAR",codeEsabora:"SONE"},
  {c:"Placo",s:"Simple",r:"BLI 675400U",n:"BOITE PLACO NO AIR Ø68 SIMPLE UNITAIRE",u:"Pièce",stock:true,fournisseur:"SONEPAR",codeEsabora:"SONE"},
  {c:"Placo",s:"Simple 32a",r:"CAP 736869",n:"CAPRICLIPS SIMPLE 32 AMPERES",u:"Pièce",stock:false,fournisseur:"SONEPAR",codeEsabora:"SONE"},
  {c:"Placo",s:"Simple 32a",r:"BLI 690860",n:"Boîtier 32 Amp. No Air D.86 prof.40",u:"Pièce",stock:false,fournisseur:"SONEPAR",codeEsabora:"SONE"},
  {c:"Placo",s:"Double",r:"BLI 620719",n:"BOITE  DOUBLE ENTRAXE 71mm",u:"Pièce",stock:false,fournisseur:"SONEPAR",codeEsabora:"SONE"},
  {c:"Placo",s:"Double",r:"BLI 682710",n:"BOITE NO AIR DOUBLE ENTRAXE 71mm",u:"Pièce",stock:false,fournisseur:"SONEPAR",codeEsabora:"SONE"},
  {c:"Placo",s:"Triple",r:"EUR 52046",n:"BOITE  TRIPLE ENTRAXE 71mm",u:"Pièce",stock:false,fournisseur:"SONEPAR",codeEsabora:"SONE"},
  {c:"Placo",s:"Triple",r:"BLI 683710",n:"BOITE NO AIR TRIPLE ENTRAXE 71mm",u:"Pièce",stock:false,fournisseur:"SONEPAR",codeEsabora:"SONE"},
  {c:"Placo",s:"Quadruple",r:"EUR 52048",n:"BOITE  QUADRUPLE ENTRAXE 71mm",u:"Pièce",stock:false,fournisseur:"SONEPAR",codeEsabora:"SONE"},
  {c:"Placo",s:"Quadruple",r:"BLI 684710",n:"BOITE NO AIR QUADRUPLE ENTRAXE 71mm",u:"Pièce",stock:false,fournisseur:"SONEPAR",codeEsabora:"SONE"},
  {c:"Placo",s:"Général",r:"BLI 685500",n:"BOITE MICRO MODULE NO AIR",u:"Pièce",stock:false,fournisseur:"SONEPAR",codeEsabora:"SONE"},
  {c:"Placo",s:"Général",r:"BLI 759020",n:"ANNEAU POUR APPAREILLAGE",u:"Pièce",stock:false,fournisseur:"SONEPAR",codeEsabora:"SONE"},
  {c:"Placo",s:"Kit Dcl + Kit Dcl Bbc",r:"BLI 610559",n:"POINT DE CENTRE BLUE BOX DCL HT55 D67",u:"Pièce",stock:false,fournisseur:"SONEPAR",codeEsabora:"SONE"},
  {c:"Placo",s:"Kit Dcl + Kit Dcl Bbc",r:"CAP 735049",n:"CAPRICLIPS POINT DE CENTRE DCL HT40 D86",u:"Pièce",stock:false,fournisseur:"SONEPAR",codeEsabora:"SONE"},
  {c:"Placo",s:"Kit Dcl + Kit Dcl Bbc",r:"BLI 670510",n:"NO AIR BBC POINT DE CENTRE DCL HT55 D67",u:"Pièce",stock:false,fournisseur:"SONEPAR",codeEsabora:"SONE"},
  {c:"Placo",s:"Kit Dcl + Kit Dcl Bbc",r:"EUR 53063",n:"Eur Ohm - Point de centre air'metic d85​​​​​​​",u:"Pièce",stock:false,fournisseur:"SONEPAR",codeEsabora:"SONE"},
  {c:"Placo",s:"Kit Dcl + Kit Dcl Bbc",r:"BLI 670860",n:"Point Centre GV No Air DCL D.86 Prof.40",u:"Pièce",stock:false,fournisseur:"SONEPAR",codeEsabora:"SONE"},
  {c:"Placo",s:"Bac D'encastrement + Porte",r:"AOE PATT0",n:"Pettite trappe affleurante pour BTT26",u:"Pièce",stock:false,fournisseur:"ATOLE",codeEsabora:"AOE"},
  {c:"Placo",s:"Bac D'encastrement + Porte",r:"AOE PATT2",n:"Porte affleurante pour BTT26",u:"Pièce",stock:false,fournisseur:"ATOLE",codeEsabora:"AOE"},
  {c:"Placo",s:"Bac D'encastrement + Porte",r:"AOE GTA203",n:"Partie démontable haute pour PATT 766*518mm",u:"Pièce",stock:false,fournisseur:"ATOLE",codeEsabora:"AOE"},
  {c:"Placo",s:"Bac D'encastrement + Porte",r:"AOE BTT20CBL",n:"Bac 2 travées PC+4R+ VA avec tableau com intégré 200 mm",u:"Pièce",stock:false,fournisseur:"ATOLE",codeEsabora:"AOE"},
  {c:"Placo",s:"Bac D'encastrement + Porte",r:"AOE BTT20CBLX3",n:"Lot de 3 Bac 2 travées PC+4R+ VA avec tableau com intégré 200 mm",u:"Pièce",stock:false,fournisseur:"ATOLE",codeEsabora:"AOE"},
  {c:"Placo",s:"Gtl",r:"GTL235ES01",n:"1 FOND 235 + 1 COUVERCLE + SANS SUPPORT + SANS EMBALLAGE",u:"Pièce",stock:false,fournisseur:"COFRELEC INDUSTRIE",codeEsabora:"COF"},
  {c:"Placo",s:"Gtl",r:"GTL235ED02",n:"1 FOND 235 + 2 COUVERCLES + 1 CLOISON + 6 SUPPORTS, CONDITIONNEE PAR 4",u:"Pièce",stock:false,fournisseur:"COFRELEC INDUSTRIE",codeEsabora:"COF"},
  {c:"Placo",s:"Gtl",r:"ELGTL00005",n:"CORNET EPANOUISSEUR POUR 1 GTL EXTRUDEE DIM 400X160",u:"Pièce",stock:false,fournisseur:"COFRELEC INDUSTRIE",codeEsabora:"COF"},
  {c:"Placo",s:"Gtl",r:"ELGTL00007",n:"CORNET EPANOUISSEUR POUR 1 GTL EXTRUDEE DIM 540X170",u:"Pièce",stock:false,fournisseur:"COFRELEC INDUSTRIE",codeEsabora:"COF"},
  {c:"Placo",s:"Gtl",r:"ELGTL00006",n:"CORNET EPANOUISSEUR POUR 1 GTL EXTRUDEE DIM 540X170",u:"Pièce",stock:false,fournisseur:"COFRELEC INDUSTRIE",codeEsabora:"COF"},
  {c:"Placo",s:"Bac D'encastrement + Porte",r:"LPE 98129",n:"MORTIER ADHESIF KRAFT 25KG MAP",u:"Pièce",stock:true,fournisseur:"SAMSE",codeEsabora:"SAM"},
  {c:"Colonne Montante",s:"Coffret De Façade",r:"BEO 0702",n:"BORNE ECP2D",u:"Pièce",stock:false,fournisseur:"BEROMET",codeEsabora:"BEO"},
  {c:"Colonne Montante",s:"Coffret De Façade",r:"BEO 0706",n:"BORNE ECP3D",u:"Pièce",stock:false,fournisseur:"BEROMET",codeEsabora:"BEO"},
  {c:"Colonne Montante",s:"Spcm",r:"BEO 1613",n:"CC 200A SPCM+cornet+2DEP.95MM2",u:"Pièce",stock:false,fournisseur:"BEROMET",codeEsabora:"BEO"},
  {c:"Colonne Montante",s:"Spcm",r:"BEO 1615",n:"CC 200A SPCM ARR 240 + CORNET",u:"Pièce",stock:false,fournisseur:"BEROMET",codeEsabora:"BEO"},
  {c:"Colonne Montante",s:"Spcm",r:"BEO 0854",n:"KIT LIAISON DIST.400A - 1 SPCM",u:"Pièce",stock:false,fournisseur:"BEROMET",codeEsabora:"BEO"},
  {c:"Colonne Montante",s:"Distributeur",r:"BEO 0960",n:"DISTRIBUTEUR ARRIVEE 200A 3 DEP CPF",u:"Pièce",stock:false,fournisseur:"BEROMET",codeEsabora:"BEO"},
  {c:"Colonne Montante",s:"Distributeur",r:"BEO 0961",n:"DISTRIBUTEUR 200A",u:"Pièce",stock:false,fournisseur:"BEROMET",codeEsabora:"BEO"},
  {c:"Colonne Montante",s:"Porte Fusible",r:"BEO 0962",n:"ENSEMBLE CPF 60A UNIVERSEL MONO",u:"Pièce",stock:false,fournisseur:"BEROMET",codeEsabora:"BEO"},
  {c:"Colonne Montante",s:"Porte Fusible",r:"BEO 0963",n:"ENSEMBLE CPF 60A UNIVERSEL TRI",u:"Pièce",stock:false,fournisseur:"BEROMET",codeEsabora:"BEO"},
  {c:"Colonne Montante",s:"Colonne De Terre",r:"BEO 3115",n:"REPARTITEUR DE TERRE 6 DERIVATIONS ALU",u:"Pièce",stock:false,fournisseur:"BEROMET",codeEsabora:"BEO"},
  {c:"Colonne Montante",s:"Colonne De Terre",r:"BEO 3116",n:"REPARTITEUR DE TERRE 12 DERIVATIONS ALU",u:"Pièce",stock:false,fournisseur:"BEROMET",codeEsabora:"BEO"},
  {c:"Colonne Montante",s:"Colonne De Terre",r:"BEO 3131",n:"BARRETTE DE COUPURE DE TERRE BASSE CUIVRE",u:"Pièce",stock:false,fournisseur:"BEROMET",codeEsabora:"BEO"},
  {c:"Colonne Montante",s:"Colonne De Terre",r:"BEO 3105",n:"BARRETTE DE COUPURE DE TERRE BASSE ALU",u:"Pièce",stock:false,fournisseur:"BEROMET",codeEsabora:"BEO"},
  {c:"Colonne Montante",s:"Colonne De Terre",r:"BEO 3106",n:"BARRETTE DE COUPURE DE TERRE BASSE ALU AVEC BOITIER",u:"Pièce",stock:false,fournisseur:"BEROMET",codeEsabora:"BEO"},
  {c:"Colonne Montante",s:"Tri",r:"BEO 0410",n:"PANNEAU 330x330 COMPTEUR TRI + DISJ.",u:"Pièce",stock:true,fournisseur:"BEROMET",codeEsabora:"BEO"},
  {c:"Colonne Montante",s:"Tri",r:"BEO 0451",n:"TAB.250x550 CBE TRI+DISJ+CONNECT.ARR.",u:"Pièce",stock:true,fournisseur:"BEROMET",codeEsabora:"BEO"},
  {c:"Colonne Montante",s:"Tri",r:"LEG 401012",n:"DISJ.BRANCH.4P 10/30A 500MA S",u:"Pièce",stock:true,fournisseur:"SONEPAR",codeEsabora:"SONE"},
  {c:"Colonne Montante",s:"Tri",r:"LEG 401013",n:"DISJ.BRANCH.4P 30/60A 500MA S",u:"Pièce",stock:true,fournisseur:"SONEPAR",codeEsabora:"SONE"},
  {c:"Colonne Montante",s:"Tri",r:"BEO 04100153",n:"PLAT.0410 + 0153 DISJ.4X10/30S",u:"Pièce",stock:false,fournisseur:"BEROMET",codeEsabora:"BEO"},
  {c:"Colonne Montante",s:"Tri",r:"BEO 04100154",n:"PLAT.0410 + 0154 DISJ.4X30/60S",u:"Pièce",stock:false,fournisseur:"BEROMET",codeEsabora:"BEO"},
  {c:"Colonne Montante",s:"Tri",r:"BEO 0175",n:"TAB.250x550 CBE + DISJ.4X10/30 S",u:"Pièce",stock:false,fournisseur:"BEROMET",codeEsabora:"BEO"},
  {c:"Colonne Montante",s:"Tri",r:"BEO 0176",n:"TAB.250x550 CBE + DISJ.4X30/60 S",u:"Pièce",stock:false,fournisseur:"BEROMET",codeEsabora:"BEO"},
  {c:"Colonne Montante",s:"Fouet",r:"BEO 3140",n:"FOUET EBCP TRI",u:"Pièce",stock:false,fournisseur:"BEROMET",codeEsabora:"BEO"},
  {c:"Colonne Montante",s:"Fouet",r:"BEO 3109",n:"FOUET EBCP MONO",u:"Pièce",stock:false,fournisseur:"BEROMET",codeEsabora:"BEO"},
  {c:"Colonne Montante",s:"Tete De Cable",r:"TRM 82914",n:"EXT. E4R 10-35²",u:"Pièce",stock:true,fournisseur:"SONEPAR",codeEsabora:"SONE"},
  {c:"Colonne Montante",s:"Tete De Cable",r:"TRM 82915",n:"EXT. E4R 50-150²",u:"Pièce",stock:true,fournisseur:"SONEPAR",codeEsabora:"SONE"},
  {c:"Colonne Montante",s:"Tete De Cable",r:"TRM 82916",n:"EXT. E4R 240²",u:"Pièce",stock:true,fournisseur:"SONEPAR",codeEsabora:"SONE"},
  {c:"Colonne Montante",s:"Tete De Cable",r:"BLI 694000",n:"BOUCHON ETANCHE NO AIR ICTA 40",u:"Pièce",stock:true,fournisseur:"SONEPAR",codeEsabora:"SONE"},
  {c:"Fils / Câbles",s:"Tronçon Alu",r:"FIL AR2V1X35TGL",n:"AR2V ALU 1X35 TGL",u:"ML",stock:false,fournisseur:"SONEPAR",codeEsabora:"SONE"},
  {c:"Fils / Câbles",s:"Tronçon Alu",r:"FIL AR2V1X50TGL",n:"AR2V ALU 1X50TGL",u:"ML",stock:true,fournisseur:"SONEPAR",codeEsabora:"SONE"},
  {c:"Fils / Câbles",s:"Tronçon Alu",r:"FIL AR2V1X70TGL",n:"AR2V ALU 1X70 TGL",u:"ML",stock:true,fournisseur:"SONEPAR",codeEsabora:"SONE"},
  {c:"Fils / Câbles",s:"Tronçon Alu",r:"FIL AR2V1X95TGL",n:"AR2V ALU 1X95 TGL",u:"ML",stock:true,fournisseur:"SONEPAR",codeEsabora:"SONE"},
  {c:"Fils / Câbles",s:"Tronçon Alu",r:"FIL AR2V1X120TGL",n:"AR2V ALU 1X120 TGL",u:"ML",stock:true,fournisseur:"SONEPAR",codeEsabora:"SONE"},
  {c:"Fils / Câbles",s:"Tronçon Cuivre",r:"FIL R2V1X35TGL",n:"R2V CU 1X35 TGL",u:"ML",stock:false,fournisseur:"SONEPAR",codeEsabora:"SONE"},
  {c:"Fils / Câbles",s:"Tronçon Cuivre",r:"FIL R2V1X50TGL",n:"R2V CU 1X50 TGL",u:"ML",stock:false,fournisseur:"SONEPAR",codeEsabora:"SONE"},
  {c:"Fils / Câbles",s:"Tronçon Cuivre",r:"FIL R2V1X70TGL",n:"R2V CU 1X70 TGL",u:"ML",stock:false,fournisseur:"SONEPAR",codeEsabora:"SONE"},
  {c:"Fils / Câbles",s:"Tronçon Cuivre",r:"FIL R2V1X95TGL",n:"R2V CU 1X95 TGL",u:"ML",stock:false,fournisseur:"SONEPAR",codeEsabora:"SONE"},
  {c:"Équipement Commun",s:"Detecteur",r:"BE4 92194",n:"DETECTEUR PD3-1C-AP SAILLIE",u:"Pièce",stock:false,fournisseur:"SONEPAR",codeEsabora:"SONE"},
  {c:"Équipement Commun",s:"Detecteur",r:"BE4 92197",n:"DETECTEUR PD3-1C-FP ENCASTRE",u:"Pièce",stock:false,fournisseur:"SONEPAR",codeEsabora:"SONE"},
  {c:"Équipement Commun",s:"Detecteur",r:"BE4 91101",n:"LC CLICK DETECTEUR 140DEG BLANC",u:"Pièce",stock:false,fournisseur:"SONEPAR",codeEsabora:"SONE"},
  {c:"Équipement Commun",s:"Detecteur",r:"BE4 91102",n:"LC CLICK DETECTEUR 200DEG BLANC",u:"Pièce",stock:false,fournisseur:"SONEPAR",codeEsabora:"SONE"},
  {c:"Équipement Commun",s:"Detecteur",r:"BE4 92144",n:"PD4N-1C-AP DETECTEUR DE MOUVEMENT EN SAILLIE",u:"Pièce",stock:false,fournisseur:"SONEPAR",codeEsabora:"SONE"},
  {c:"Équipement Commun",s:"Detecteur",r:"BE4 92149",n:"PD4N-1C-FP DETECTEUR DE MOUVEMENT FAUX PLAFOND",u:"Pièce",stock:false,fournisseur:"SONEPAR",codeEsabora:"SONE"},
  {c:"Équipement Commun",s:"Detecteur",r:"YUX EP10428746",n:"Détecteur de mouvement de plafond MD-FLAT 360i/8 BK ENCASTRE",u:"Pièce",stock:false,fournisseur:"CEA63",codeEsabora:"CEA63"},
  {c:"Équipement Commun",s:"Detecteur",r:"YUX EP10055416",n:"Détecteur de mouvement de plafond MD-C 360i/8 BK SAILLI",u:"Pièce",stock:false,fournisseur:"CEA63",codeEsabora:"CEA63"},
  {c:"Équipement Commun",s:"Report Defaut",r:"SCH NU3772",n:"Voyant 230V vert rouge inco 2m",u:"Pièce",stock:false,fournisseur:"SONEPAR",codeEsabora:"SONE"},
  {c:"Équipement Commun",s:"Report Defaut",r:"SCH NU7002PC",n:"Support fixation 2m plastique",u:"Pièce",stock:false,fournisseur:"SONEPAR",codeEsabora:"SONE"},
  {c:"Équipement Commun",s:"Report Defaut",r:"SCH NU400218",n:"Plaque de finition Blanc 1P",u:"Pièce",stock:false,fournisseur:"SONEPAR",codeEsabora:"SONE"},
  {c:"Équipement Commun",s:"Tableau + Gtl",r:"SCH R9H13401",n:"TABLEAU 1 RANGEE",u:"Pièce",stock:false,fournisseur:"SONEPAR",codeEsabora:"SONE"},
  {c:"Équipement Commun",s:"Tableau + Gtl",r:"SCH R9H13402",n:"TABLEAU 2 RANGEES",u:"Pièce",stock:false,fournisseur:"SONEPAR",codeEsabora:"SONE"},
  {c:"Équipement Commun",s:"Tableau + Gtl",r:"DIG 07813",n:"TABLEAU 3 RANGEES",u:"Pièce",stock:true,fournisseur:"SATAIR",codeEsabora:"SAT"},
  {c:"Équipement Commun",s:"Tableau + Gtl",r:"SCH R9HKT13",n:"kit goulotte GTL 13M",u:"Pièce",stock:false,fournisseur:"SONEPAR",codeEsabora:"SONE"},
  {c:"Équipement Commun",s:"Tableau + Gtl",r:"SCH R9HKT18",n:"kit goulotte GTL 18M",u:"Pièce",stock:false,fournisseur:"SONEPAR",codeEsabora:"SONE"},
  {c:"Équipement Commun",s:"B.a.e.s. Commun",r:"ZEM LXF3017EX",n:"BAEH XENA FLAT SATI 5H 8LM IP42/IK04 NP NF NI-CD 1.2W",u:"Pièce",stock:false,fournisseur:"ZEMPER",codeEsabora:"ZEM"},
  {c:"Équipement Commun",s:"B.a.e.s. Commun",r:"ZEM 90091NMF",n:"PORTE ETIQUETTE ENCASTRE XENA-DIANA-PICTO NON INCLUS",u:"Pièce",stock:false,fournisseur:"ZEMPER",codeEsabora:"ZEM"},
  {c:"Équipement Commun",s:"B.a.e.s. Commun",r:"ZEM APV000OP",n:"ETIQUETTE ADHESIVE OPAQUE MILTIDIRECTION - XENA - FORMAT 390",u:"Pièce",stock:false,fournisseur:"ZEMPER",codeEsabora:"ZEM"},
  {c:"Équipement Commun",s:"Dad",r:"FRA NEU4710R1C",n:"DECLENCHEUR MANUEL ROUGE 1 CONTACT + CAPOT",u:"Pièce",stock:false,fournisseur:"FRANCOFA EURODIS",codeEsabora:"FRA"},
  {c:"Équipement Commun",s:"Dad",r:"FRA FINCARAIBES1",n:"DAD SECOURU AVEC 2 BATTERIES 12V 1.2AH",u:"Pièce",stock:false,fournisseur:"FRANCOFA EURODIS",codeEsabora:"FRA"},
  {c:"Équipement Commun",s:"Dad",r:"FRA FINSEXTANTDOC",n:"DETECTEUR OPTIQUE FUMEE CONVENTIONNEL SEXTANT 12/24V + SOCLE",u:"Pièce",stock:false,fournisseur:"FRANCOFA EURODIS",codeEsabora:"FRA"},
  {c:"Équipement Commun",s:"Coupure Pompier",r:"GEW FR60161",n:"COFFRET CHAUFFERIE MONOPHASÉ",u:"Pièce",stock:false,fournisseur:"SONEPAR",codeEsabora:"SONE"},
  {c:"Équipement Commun",s:"Coupure Pompier",r:"GEW FR60160",n:"COFFRET CHAUFFERIE TRI+NEUTRE",u:"Pièce",stock:false,fournisseur:"SONEPAR",codeEsabora:"SONE"},
  {c:"Équipement Commun",s:"Coupure Pompier",r:"GW42201",n:"COFFRET IP55 SYST.SECUR.AVEC BOUT.POUSSO",u:"Pièce",stock:false,fournisseur:"SONEPAR",codeEsabora:"SONE"},
  {c:"Équipement Logement",s:"Odace",r:"SCH S523059P",n:"LOT DE 40 PC",u:"Pièce",stock:false,fournisseur:"SONEPAR",codeEsabora:"SONE"},
  {c:"Équipement Logement",s:"Odace",r:"SCH S523204P",n:"LOT DE 60 VA ET VIENT",u:"Pièce",stock:false,fournisseur:"SONEPAR",codeEsabora:"SONE"},
  {c:"Équipement Logement",s:"Odace",r:"SCH S520059",n:"PC",u:"Pièce",stock:false,fournisseur:"SONEPAR",codeEsabora:"SONE"},
  {c:"Équipement Logement",s:"Odace",r:"SCH S520276",n:"BP VOYANT",u:"Pièce",stock:false,fournisseur:"SONEPAR",codeEsabora:"SONE"},
  {c:"Équipement Logement",s:"Odace",r:"SCH S520204",n:"VA ET VIENT",u:"Pièce",stock:false,fournisseur:"SONEPAR",codeEsabora:"SONE"},
  {c:"Équipement Logement",s:"Odace",r:"SCH S520263",n:"INTER VOYANT",u:"Pièce",stock:false,fournisseur:"SONEPAR",codeEsabora:"SONE"},
  {c:"Équipement Logement",s:"Odace",r:"SCH S520263",n:"VA ET VIENT LUMINEUX",u:"Pièce",stock:false,fournisseur:"SONEPAR",codeEsabora:"SONE"},
  {c:"Équipement Logement",s:"Odace",r:"SCH S520214",n:"DOUBLE VA ET VIENT",u:"Pièce",stock:false,fournisseur:"SONEPAR",codeEsabora:"SONE"},
  {c:"Équipement Logement",s:"Odace",r:"SCH S520206",n:"BOUTON POUSSOIR",u:"Pièce",stock:false,fournisseur:"SONEPAR",codeEsabora:"SONE"},
  {c:"Équipement Logement",s:"Odace",r:"SCH S520246",n:"BP SONNETTE",u:"Pièce",stock:false,fournisseur:"SONEPAR",codeEsabora:"SONE"},
  {c:"Équipement Logement",s:"Odace",r:"SCH S520208",n:"MONTE ET BAISSE VR",u:"Pièce",stock:false,fournisseur:"SONEPAR",codeEsabora:"SONE"},
  {c:"Équipement Logement",s:"Odace",r:"SCH S520451",n:"TV/FM",u:"Pièce",stock:false,fournisseur:"SONEPAR",codeEsabora:"SONE"},
  {c:"Équipement Logement",s:"Odace",r:"SCH S520461",n:"TV/FM/SAT",u:"Pièce",stock:false,fournisseur:"SONEPAR",codeEsabora:"SONE"},
  {c:"Équipement Logement",s:"Odace",r:"SCH VDIB1772XB12",n:"NOYAUX  ONE RJ45 CAT6A BLINDE",u:"Pièce",stock:false,fournisseur:"SONEPAR",codeEsabora:"SONE"},
  {c:"Équipement Logement",s:"Odace",r:"SCH S520400",n:"SUPPORT RJ 45 SIMPLE",u:"Pièce",stock:false,fournisseur:"SONEPAR",codeEsabora:"SONE"},
  {c:"Équipement Logement",s:"Odace",r:"SCH S520410",n:"SUPPORT RJ 45 DOUBLE",u:"Pièce",stock:false,fournisseur:"SONEPAR",codeEsabora:"SONE"},
  {c:"Équipement Logement",s:"Odace",r:"SCH S520299",n:"SACHET DE RESSORT ODACE",u:"Pièce",stock:false,fournisseur:"SONEPAR",codeEsabora:"SONE"},
  {c:"Équipement Logement",s:"Odace",r:"SCH S520666",n:"OBTURATEUR",u:"Pièce",stock:false,fournisseur:"SONEPAR",codeEsabora:"SONE"},
  {c:"Équipement Logement",s:"Odace",r:"SCH S520291",n:"ACCESSOIRE VOYANT LED BASSE CONSO (PAR CABLE)",u:"Pièce",stock:false,fournisseur:"SONEPAR",codeEsabora:"SONE"},
  {c:"Équipement Logement",s:"Odace",r:"SCH S520702",n:"PLAQUE SIMPLE ODACE STYL",u:"Pièce",stock:false,fournisseur:"SONEPAR",codeEsabora:"SONE"},
  {c:"Équipement Logement",s:"Odace",r:"SCH S520704",n:"PLAQUE DOUBLE ODACE STYL",u:"Pièce",stock:false,fournisseur:"SONEPAR",codeEsabora:"SONE"},
  {c:"Équipement Logement",s:"Odace",r:"SCH S520706",n:"PLAQUE TRIPLE ODACE STYL",u:"Pièce",stock:false,fournisseur:"SONEPAR",codeEsabora:"SONE"},
  {c:"Équipement Logement",s:"Odace",r:"SCH S520708",n:"PLAQUE QUADRUPLE ODACE STYL",u:"Pièce",stock:false,fournisseur:"SONEPAR",codeEsabora:"SONE"},
  {c:"Équipement Logement",s:"Odace",r:"SCH S523702P",n:"LOT DE 100 PLAQUES ODACE STYL",u:"Pièce",stock:false,fournisseur:"SONEPAR",codeEsabora:"SONE"},
  {c:"Équipement Logement",s:"Odace",r:"SCH S520802",n:"PLAQUE ODACE TOUCH",u:"Pièce",stock:false,fournisseur:"SONEPAR",codeEsabora:"SONE"},
  {c:"Équipement Logement",s:"Odace",r:"SCH S520804",n:"PLAQUE DOUBLE ODACE TOUCH",u:"Pièce",stock:false,fournisseur:"SONEPAR",codeEsabora:"SONE"},
  {c:"Équipement Logement",s:"Odace",r:"SCH S520806",n:"PLAQUE TRIPLE ODACE TOUCH",u:"Pièce",stock:false,fournisseur:"SONEPAR",codeEsabora:"SONE"},
  {c:"Équipement Logement",s:"Odace",r:"SCH S520808",n:"PLAQUE QUADRUPLE ODACE TOUCH",u:"Pièce",stock:false,fournisseur:"SONEPAR",codeEsabora:"SONE"},
  {c:"Équipement Logement",s:"Odace",r:"SCH S520519",n:"VARIATEUR UNIVERSEL - BLANC - LED 400W",u:"Pièce",stock:false,fournisseur:"SONEPAR",codeEsabora:"SONE"},
  {c:"Équipement Logement",s:"Odace",r:"SCH S520523",n:"ODACE DETECT TT CHARG BLC",u:"Pièce",stock:false,fournisseur:"SONEPAR",codeEsabora:"SONE"},
  {c:"Équipement Logement",s:"Ovalis",r:"SCH S320059P",n:"LOT 108 2P+T A PUITS BLANC",u:"Pièce",stock:false,fournisseur:"SONEPAR",codeEsabora:"SONE"},
  {c:"Équipement Logement",s:"Ovalis",r:"SCH S320052P",n:"LOT 108 2P+T AFFLEURANTE BLANC",u:"Pièce",stock:false,fournisseur:"SONEPAR",codeEsabora:"SONE"},
  {c:"Équipement Logement",s:"Ovalis",r:"SCH S320204P",n:"LOT 108 VA ET VIENT BLANC",u:"Pièce",stock:false,fournisseur:"SONEPAR",codeEsabora:"SONE"},
  {c:"Équipement Logement",s:"Ovalis",r:"SCH  S320214P",n:"LOT 108 DOUBLE VV BLANC",u:"Pièce",stock:false,fournisseur:"SONEPAR",codeEsabora:"SONE"},
  {c:"Équipement Logement",s:"Ovalis",r:"SCH  S320476P",n:"LOT 108 RJ45 CAT6 STP BLANC",u:"Pièce",stock:false,fournisseur:"SONEPAR",codeEsabora:"SONE"},
  {c:"Équipement Logement",s:"Ovalis",r:"SCH S320059",n:"PC 2P+T A PUITS BLANC",u:"Pièce",stock:false,fournisseur:"SONEPAR",codeEsabora:"SONE"},
  {c:"Équipement Logement",s:"Ovalis",r:"SCH S320052",n:"PC 2P+T AFFLEURANTE BLANC",u:"Pièce",stock:false,fournisseur:"SONEPAR",codeEsabora:"SONE"},
  {c:"Équipement Logement",s:"Ovalis",r:"SCH S320204",n:"VA ET VIENT BLANC",u:"Pièce",stock:false,fournisseur:"SONEPAR",codeEsabora:"SONE"},
  {c:"Équipement Logement",s:"Ovalis",r:"SCH  S320214",n:"DOUBLE VV BLANC",u:"Pièce",stock:false,fournisseur:"SONEPAR",codeEsabora:"SONE"},
  {c:"Équipement Logement",s:"Ovalis",r:"SCH S320206",n:"POUSSOIR FERMETURE BLANC",u:"Pièce",stock:false,fournisseur:"SONEPAR",codeEsabora:"SONE"},
  {c:"Équipement Logement",s:"Ovalis",r:"SCH S320266",n:"POUSSOIR PORTE ETIQUETTE BLANC",u:"Pièce",stock:false,fournisseur:"SONEPAR",codeEsabora:"SONE"},
  {c:"Équipement Logement",s:"Ovalis",r:"SCH S320666",n:"OBTURATEUR BLANC",u:"Pièce",stock:false,fournisseur:"SONEPAR",codeEsabora:"SONE"},
  {c:"Équipement Logement",s:"Ovalis",r:"SCH S320208",n:"INTER VOLET ROULANT BLANC",u:"Pièce",stock:false,fournisseur:"SONEPAR",codeEsabora:"SONE"},
  {c:"Équipement Logement",s:"Ovalis",r:"SCH S320216",n:"DOUBLE POUSSOIR BLANC",u:"Pièce",stock:false,fournisseur:"SONEPAR",codeEsabora:"SONE"},
  {c:"Équipement Logement",s:"Ovalis",r:"SCH S320263",n:"VA ET VIENT LUM+LAMPE BLANC",u:"Pièce",stock:false,fournisseur:"SONEPAR",codeEsabora:"SONE"},
  {c:"Équipement Logement",s:"Ovalis",r:"SCH S320285",n:"COMBI VV + POUSSOIR BLANC",u:"Pièce",stock:false,fournisseur:"SONEPAR",codeEsabora:"SONE"},
  {c:"Équipement Logement",s:"Ovalis",r:"SCH  S320476",n:"RJ45 CAT6 STP BLANC",u:"Pièce",stock:false,fournisseur:"SONEPAR",codeEsabora:"SONE"},
  {c:"Équipement Logement",s:"Ovalis",r:"SCH S320451",n:"PRISE TV - R BLANC",u:"Pièce",stock:false,fournisseur:"SONEPAR",codeEsabora:"SONE"},
  {c:"Équipement Logement",s:"Ovalis",r:"SCH S320461",n:"PRISE TV-R-SAT BLANC",u:"Pièce",stock:false,fournisseur:"SONEPAR",codeEsabora:"SONE"},
  {c:"Équipement Logement",s:"Ovalis",r:"SCH S320519",n:"VARIATEUR",u:"Pièce",stock:false,fournisseur:"SONEPAR",codeEsabora:"SONE"},
  {c:"Équipement Logement",s:"Ovalis",r:"SCH S320236",n:"POUSSOIR VMC BLANC",u:"Pièce",stock:false,fournisseur:"SONEPAR",codeEsabora:"SONE"},
  {c:"Équipement Logement",s:"Ovalis",r:"SCH S320523",n:"DETECTEUR DE MOUVEMENT / PRÉSENCE",u:"Pièce",stock:false,fournisseur:"SONEPAR",codeEsabora:"SONE"},
  {c:"Équipement Logement",s:"Ovalis",r:"SCH S320702P",n:"LOT 360 PLAQUES 1P BLANC",u:"Pièce",stock:false,fournisseur:"SONEPAR",codeEsabora:"SONE"},
  {c:"Équipement Logement",s:"Ovalis",r:"SCH S320704P",n:"LOT 180 PLAQUES 2P HOR BLANC",u:"Pièce",stock:false,fournisseur:"SONEPAR",codeEsabora:"SONE"},
  {c:"Équipement Logement",s:"Ovalis",r:"SCH S320702",n:"PLAQUE 1 POST BLANC",u:"Pièce",stock:false,fournisseur:"SONEPAR",codeEsabora:"SONE"},
  {c:"Équipement Logement",s:"Ovalis",r:"SCH S320704",n:"PLAQUE 2 POST HORIZ 71MM BLANC",u:"Pièce",stock:false,fournisseur:"SONEPAR",codeEsabora:"SONE"},
  {c:"Équipement Logement",s:"Ovalis",r:"SCH S320724",n:"PLAQUE 2 POST VERT 71MM BLANC",u:"Pièce",stock:false,fournisseur:"SONEPAR",codeEsabora:"SONE"},
  {c:"Équipement Logement",s:"Ovalis",r:"SCH S320706",n:"PLAQUE 3 POST HORIZ 71MM BLANC",u:"Pièce",stock:false,fournisseur:"SONEPAR",codeEsabora:"SONE"},
  {c:"Équipement Logement",s:"Ovalis",r:"SCH S320726",n:"PLAQUE 3 POST VERT 71MM BLANC",u:"Pièce",stock:false,fournisseur:"SONEPAR",codeEsabora:"SONE"},
  {c:"Équipement Logement",s:"Ovalis",r:"SCH S320708",n:"PLAQUE 4 POST HORIZ 71MM BLANC",u:"Pièce",stock:false,fournisseur:"SONEPAR",codeEsabora:"SONE"},
  {c:"Équipement Logement",s:"Sortie De Cable",r:"BLI 605201",n:"SORTIE DE CABLE 16A",u:"Pièce",stock:false,fournisseur:"SONEPAR",codeEsabora:"SONE"},
  {c:"Équipement Logement",s:"Sortie De Cable",r:"BLI 605320",n:"SORTIE DE CABLE 32A",u:"Pièce",stock:false,fournisseur:"SONEPAR",codeEsabora:"SONE"},
  {c:"Équipement Logement",s:"Sortie De Cable",r:"BLI 605211",n:"SORTIE DE CABLE 16A IP44",u:"Pièce",stock:false,fournisseur:"SONEPAR",codeEsabora:"SONE"},
  {c:"Équipement Logement",s:"Sortie De Cable",r:"BLI 605215",n:"SORTIE DE CABLE 16A GRIFFES",u:"Pièce",stock:false,fournisseur:"SONEPAR",codeEsabora:"SONE"},
  {c:"Équipement Logement",s:"Sortie De Cable",r:"EUR 60087",n:"SORTIE DE CABLE 32A GRIFFES",u:"Pièce",stock:false,fournisseur:"SONEPAR",codeEsabora:"SONE"},
  {c:"Équipement Logement",s:"Dcl",r:"BLI 600800",n:"COUVERCLE D'APPLIQUE Ø67",u:"Pièce",stock:false,fournisseur:"SONEPAR",codeEsabora:"SONE"},
  {c:"Équipement Logement",s:"Dcl",r:"BLI 601200",n:"COUVERCLE DCL Ø120",u:"Pièce",stock:false,fournisseur:"SONEPAR",codeEsabora:"SONE"},
  {c:"Équipement Logement",s:"Dcl",r:"EUR 53042F",n:"Couv. de finition DCL d 120 IP44 avec membrane caoutchouc",u:"Pièce",stock:false,fournisseur:"SONEPAR",codeEsabora:"SONE"},
  {c:"Équipement Logement",s:"Dcl",r:"BLI 601300",n:"COUVERCLE DCL Ø130",u:"Pièce",stock:false,fournisseur:"SONEPAR",codeEsabora:"SONE"},
  {c:"Équipement Logement",s:"Douille + Fiche",r:"BLI 710100",n:"DOUILLE E27 + FICHE DCL",u:"Pièce",stock:false,fournisseur:"SONEPAR",codeEsabora:"SONE"},
  {c:"Équipement Logement",s:"Douille + Fiche",r:"BLI 710110",n:"FICHE DCL",u:"Pièce",stock:false,fournisseur:"SONEPAR",codeEsabora:"SONE"},
  {c:"Équipement Logement",s:"Piton",r:"BLI 754110",n:"PITON L 85mm",u:"Pièce",stock:false,fournisseur:"SONEPAR",codeEsabora:"SONE"},
  {c:"Équipement Logement",s:"Piton",r:"BLI 750192",n:"PITON L 100mm",u:"Pièce",stock:false,fournisseur:"SONEPAR",codeEsabora:"SONE"},
  {c:"Équipement Logement",s:"Piton",r:"BLI 750193",n:"PITON L 120mm",u:"Pièce",stock:false,fournisseur:"SONEPAR",codeEsabora:"SONE"},
  {c:"Équipement Logement",s:"Piton",r:"BLI 750194",n:"PITON L 130mm",u:"Pièce",stock:false,fournisseur:"SONEPAR",codeEsabora:"SONE"},
  {c:"Équipement Logement",s:"Piton",r:"SIB P0039940",n:"Piton + ressort lame pour boite Ø100",u:"Pièce",stock:false,fournisseur:"SONEPAR",codeEsabora:"SONE"},
  {c:"Équipement Logement",s:"Couvercle Vierge",r:"SIB P0221090",n:"Couvercle de finition diametre ext 82",u:"Pièce",stock:false,fournisseur:"SONEPAR",codeEsabora:"SONE"},
  {c:"Équipement Logement",s:"Couvercle Vierge",r:"SIB P0221091",n:"Couvercle de finition diametre ext 70",u:"Pièce",stock:false,fournisseur:"SONEPAR",codeEsabora:"SONE"},
  {c:"Équipement Logement",s:"Couvercle Vierge",r:"SIB P03210",n:"Couvercle finition petite et grande tete de pieuvre Ø85",u:"Pièce",stock:false,fournisseur:"SONEPAR",codeEsabora:"SONE"},
  {c:"Équipement Logement",s:"Couvercle Vierge",r:"SIB P0211048",n:"Couvercle finition petite et grande tete de pieuvre Ø100",u:"Pièce",stock:false,fournisseur:"SONEPAR",codeEsabora:"SONE"},
  {c:"Équipement Logement",s:"Seche-serviette",r:"ATL 831416",n:"SECHE-SERVIETTE DEVO-DCB18 500W",u:"Pièce",stock:false,fournisseur:"SONEPAR",codeEsabora:"SONE"},
  {c:"Équipement Logement",s:"Seche-serviette",r:"ATL 831417",n:"SECHE-SERVIETTE DEVO-DCB18 750W",u:"Pièce",stock:false,fournisseur:"SONEPAR",codeEsabora:"SONE"},
  {c:"Équipement Logement",s:"Appareillage Special",r:"LEG 081988",n:"BOITE D'ENCASTREMENT PRISE DE SOL",u:"Pièce",stock:false,fournisseur:"SONEPAR",codeEsabora:"SONE"},
  {c:"Équipement Logement",s:"Appareillage Special",r:"LEG 089760",n:"PRISE SOL 2P+T 16A CARRÉE IB",u:"Pièce",stock:false,fournisseur:"SONEPAR",codeEsabora:"SONE"},
  {c:"Équipement Logement",s:"Appareillage Special",r:"LEG 089770",n:"PRISE SOL 2P+T 16A RONDE IB",u:"Pièce",stock:false,fournisseur:"SONEPAR",codeEsabora:"SONE"},
  {c:"Équipement Logement",s:"Divers",r:"POI MM100TC",n:"COMPTEUR ELECTRIQUE MONOPHASE 100 A AVEC TRANSFORM",u:"Pièce",stock:false,fournisseur:"POLIER",codeEsabora:"POLI"},
  {c:"Équipement Logement",s:"Divers",r:"LCI 031276",n:"compteur multi-mesure monophasé, sur TI 100A fourni",u:"Pièce",stock:false,fournisseur:"REXEL",codeEsabora:"REX"},
  {c:"Équipement Logement",s:"Divers",r:"SAT DIG04924",n:"COMPTEUR WIFI MONO + TORE OUVRANT 60A - DIGITAL ELECTRIC",u:"Pièce",stock:false,fournisseur:"SATAIR",codeEsabora:"SAT"},
  {c:"Courant Faible",s:"Tv",r:"AOE GTC113",n:"Répartiteur TV/SAT 3 sorties-1 entrée",u:"Pièce",stock:false,fournisseur:"ATOLE",codeEsabora:"AOE"},
  {c:"Courant Faible",s:"RJ45",r:"BLI 731110",n:"Lot de 100 noyaux RJ45 G3",u:"Pièce",stock:false,fournisseur:"SONEPAR",codeEsabora:"SONE"},
  {c:"Courant Faible",s:"RJ45",r:"BLI 731110U",n:"Noyaux RJ45 G3",u:"Pièce",stock:true,fournisseur:"SONEPAR",codeEsabora:"SONE"},
  {c:"Courant Faible",s:"Répartiteur Tv / Rj45",r:"EVC ABS021RJKIT",n:"KIT REPARTITEUR ULB 2 DIR. F/RJ45 + 2 CORDONS RJ/RJ PLATS",u:"Pièce",stock:false,fournisseur:"SATAIR",codeEsabora:"SAT"},
  {c:"Courant Faible",s:"Répartiteur Tv / Rj45",r:"EVC ABS041RJKIT",n:"KIT REPARTITEUR ULB 4 DIR. F/RJ45 + 4 CORDONS RJ/RJ PLATS",u:"Pièce",stock:false,fournisseur:"SATAIR",codeEsabora:"SAT"},
  {c:"Courant Faible",s:"Répartiteur Tv / Rj45",r:"BLI 731102",n:"Prise simple 2P+T encastrable 45x45 mm",u:"Pièce",stock:false,fournisseur:"SONEPAR",codeEsabora:"SONE"},
  {c:"Courant Faible",s:"Répartiteur Tv / Rj45",r:"SAT DECDCP1PCDBC003",n:"PRISE PC 2PLOT +TERRE DROITE BLANCHE ENCASTRABLE 45X45",u:"Pièce",stock:false,fournisseur:"SATAIR",codeEsabora:"SAT"},
  {c:"Courant Faible",s:"Fibre optique",r:"RTSB-70-001015",n:"PBO T2 Boîtier pour point de branchement V2 - vide",u:"Pièce",stock:false,fournisseur:"TETRADIS",codeEsabora:"TETR"},
  {c:"Courant Faible",s:"Fibre optique",r:"RTSB-01-100160",n:"Cassette 12 fusions 1pas",u:"Pièce",stock:false,fournisseur:"TETRADIS",codeEsabora:"TETR"},
  {c:"Courant Faible",s:"Fibre optique",r:"RTSB-01-100161",n:"Cassette 24 Fusions 1pas pour BPEO & PBO",u:"Pièce",stock:false,fournisseur:"TETRADIS",codeEsabora:"TETR"},
  {c:"Courant Faible",s:"Fibre optique",r:"RTSB-73-911111000",n:"PTO THD FACTORY 1FO équipée 1Rac&1Pigtail SC-APC",u:"Pièce",stock:false,fournisseur:"TETRADIS",codeEsabora:"TETR"},
  {c:"Courant Faible",s:"Fibre optique",r:"RTSB-73-943144000",n:"Lot de 10 PTO THD FACTORY 80/80 4FO SCAPC",u:"Pièce",stock:false,fournisseur:"TETRADIS",codeEsabora:"TETR"},
  {c:"Courant Faible",s:"Fibre optique",r:"RTSB-73-913111030",n:"KIT PTO/DTIO THD FACTORY 1FO SCAPC LSZH 30M",u:"Pièce",stock:false,fournisseur:"TETRADIS",codeEsabora:"TETR"},
  {c:"Courant Faible",s:"Fibre optique",r:"TET RTSB-73-913111050",n:"KIT PTO THD FACTORY 1FO SCAPC LSZH 50M",u:"Pièce",stock:false,fournisseur:"TETRADIS",codeEsabora:"TETR"},
  {c:"Courant Faible",s:"Fibre optique",r:"RTSB-73-993144030",n:"KIT DTIO MOD THD FACTORY 4FO SCAPC LSZH 30M",u:"Pièce",stock:false,fournisseur:"TETRADIS",codeEsabora:"TETR"},
  {c:"Courant Faible",s:"Fibre optique",r:"TET RTSB-73-943144050",n:"KIT PTO THD FACTORY 4FO SCAPC LSZH 50M",u:"Pièce",stock:false,fournisseur:"TETRADIS",codeEsabora:"TETR"},
  {c:"Courant Faible",s:"Fibre optique",r:"TET CTSH-33-246024N",n:"Câble Colonne mte M6 G657A2 LSZH FRP LAT 24FO",u:"Pièce",stock:false,fournisseur:"TETRADIS",codeEsabora:"TETR"},
  {c:"Courant Faible",s:"Fibre optique",r:"TET CTSH-33-246048N",n:"Câble Colonne mte M6 G657A2 LSZH FRP LAT 48FO",u:"Pièce",stock:false,fournisseur:"TETRADIS",codeEsabora:"TETR"},
  {c:"Courant Faible",s:"Fibre optique",r:"TET CTSH-33-246096N",n:"Câble Colonne mte M6 G657A2 LSZH FRP LAT 96FO",u:"Pièce",stock:false,fournisseur:"TETRADIS",codeEsabora:"TETR"},
  {c:"Courant Faible",s:"Colonne + Antenne Tv",r:"MAE 0145332R13",n:"ANTENNE TNT 13DB LTE 700-5G",u:"Pièce",stock:false,fournisseur:"SATAIR",codeEsabora:"SAT"},
  {c:"Courant Faible",s:"Colonne + Antenne Tv",r:"EVC EALBPROG32L",n:"AMPLIFICATEUR 50 DB PROGRAMMABLE 32 CANAUX A TRES HAUTE SELE",u:"Pièce",stock:false,fournisseur:"SATAIR",codeEsabora:"SAT"},
  {c:"Courant Faible",s:"Colonne + Antenne Tv",r:"EVC AWC611",n:"DERIVATEUR TERMINAL 5 - 1 220 MHZ 6 SORTIES -11 DB",u:"Pièce",stock:false,fournisseur:"SATAIR",codeEsabora:"SAT"},
  {c:"Courant Faible",s:"Colonne + Antenne Tv",r:"EVC AWC408",n:"DERIVATEUR TERMINAL 5 - 1 220 MHZ 4 SORTIES -8 DB",u:"Pièce",stock:false,fournisseur:"SATAIR",codeEsabora:"SAT"},
  {c:"Courant Faible",s:"Colonne + Antenne Tv",r:"EVC AWC812",n:"DERIVATEUR TERMINAL 5 - 1 220 MHZ 8 SORTIES -12 DB",u:"Pièce",stock:false,fournisseur:"SATAIR",codeEsabora:"SAT"},
  {c:"Courant Faible",s:"Colonne + Antenne Tv",r:"EVC ABS021RJKIT",n:"KIT REPARTITEUR ULB 2 DIR. F/RJ45 + 2 CORDONS RJ/RJ PLATS +",u:"Pièce",stock:false,fournisseur:"SATAIR",codeEsabora:"SAT"},
  {c:"Courant Faible",s:"Colonne + Antenne Tv",r:"EVC ABS041RJKIT",n:"KIT REPARTITEUR ULB 4 DIR. F/RJ45 + 4 CORDONS RJ/RJ PLATS +",u:"Pièce",stock:false,fournisseur:"SATAIR",codeEsabora:"SAT"},
  {c:"Courant Faible",s:"Colonne + Antenne Tv",r:"EVC EPRI2SDIN",n:"AMPLIFICATEUR D'APPARTEMENT TV + SAT 2 SORTIES",u:"Pièce",stock:false,fournisseur:"SATAIR",codeEsabora:"SAT"},
  {c:"Courant Faible",s:"Colonne + Antenne Tv",r:"EVC EPRI224",n:"AMPLIFICATEUR D'APPARTEMENT TV REGLABLE 2 SORTIES",u:"Pièce",stock:false,fournisseur:"SATAIR",codeEsabora:"SAT"},
  {c:"Courant Faible",s:"Colonne + Antenne Tv",r:"SAT ANT-DPA001",n:"AMPLIFICATEUR PROGRAMMABLE 55DB 32 CANAUX 3E V/ U 1E FMFILTRE 4G/ 5G ANTTRON",u:"Pièce",stock:false,fournisseur:"SATAIR",codeEsabora:"SAT"},
  {c:"Courant Faible",s:"Colonne + Antenne Tv",r:"SAT 6831",n:"PATTE EN M DEP.200MM GALVANISE",u:"Pièce",stock:false,fournisseur:"SATAIR",codeEsabora:"SAT"},
  {c:"Courant Faible",s:"Colonne + Antenne Tv",r:"SAT OPT-4015",n:"MAT D.40MM L.1,5M EMBOITABLE GALVANISE",u:"Pièce",stock:false,fournisseur:"SATAIR",codeEsabora:"SAT"},
  {c:"Courant Faible",s:"Colonne + Antenne Tv",r:"SAT OPT-50151",n:"MAT D.50MM L.1,5M EMBOITABLE GALVANISE",u:"Pièce",stock:false,fournisseur:"SATAIR",codeEsabora:"SAT"},
  {c:"Courant Faible",s:"Colonne + Antenne Tv",r:"MAE 0140880",n:"ANT SMC 100 V2 MONTURE LONGUE",u:"Pièce",stock:false,fournisseur:"SATAIR",codeEsabora:"SAT"},
  {c:"Courant Faible",s:"Colonne + Antenne Tv",r:"MAE 0914801R13",n:"CONV QUATTRO > 4 SORTIES",u:"Pièce",stock:false,fournisseur:"SATAIR",codeEsabora:"SAT"},
  {c:"Courant Faible",s:"Colonne + Antenne Tv",r:"D3EES45033",n:"ECO-TAXE",u:"Pièce",stock:false,fournisseur:"",codeEsabora:""},
  {c:"Courant Faible",s:"Colonne + Antenne Tv",r:"MAE 0914513",n:"SUPP 6° REG ÉLEV PR SMC100/120",u:"Pièce",stock:false,fournisseur:"SATAIR",codeEsabora:"SAT"},
  {c:"Courant Faible",s:"Colonne + Antenne Tv",r:"SAT FVS4P",n:"REPARTITEUR 4D BLINDE F ULB PASSAGE CC",u:"Pièce",stock:false,fournisseur:"SATAIR",codeEsabora:"SAT"},
  {c:"Courant Faible",s:"Colonne + Antenne Tv",r:"SAT FAG-85278",n:"DERIVATEUR 6D 5/ 2300 MHZ -15DB DER615 - FAGOR",u:"Pièce",stock:false,fournisseur:"SATAIR",codeEsabora:"SAT"},
  {c:"Courant Faible",s:"Colonne + Antenne Tv",r:"SAT FAG-85281",n:"DERIVATEUR ULB 8D 5/ 2300 MHZ -15DB DER815 - FAGOR",u:"Pièce",stock:false,fournisseur:"SATAIR",codeEsabora:"SAT"},
  {c:"Courant Faible",s:"Colonne + Antenne Tv",r:"EVC AWC408",n:"DERIVATEUR TERMINAL 5 - 1 220 MHZ 4 SORTIES -8 DB",u:"Pièce",stock:false,fournisseur:"SATAIR",codeEsabora:"SAT"},
  {c:"Courant Faible",s:"Colonne + Antenne Tv",r:"EVC SREP804",n:"REPARTITEUR SYMETRIQUE POUR COMMUTATION 8 X 8 BIS.",u:"Pièce",stock:false,fournisseur:"SATAIR",codeEsabora:"SAT"},
  {c:"Courant Faible",s:"Colonne + Antenne Tv",r:"EVC SCSC9208U",n:"COMMUTATEUR UNIVERSEL 9 CABLES 8 SAT. + TERRESTRE, 8 SORTIES",u:"Pièce",stock:false,fournisseur:"SATAIR",codeEsabora:"SAT"},
  {c:"Courant Faible",s:"Colonne + Antenne Tv",r:"EVC SCSC9212U",n:"COMMUTATEUR UNIVERSEL 9 CABLES 8 SAT. + TERRESTRE, 12 SORTIE",u:"Pièce",stock:false,fournisseur:"SATAIR",codeEsabora:"SAT"},
  {c:"Courant Faible",s:"Colonne + Antenne Tv",r:"EVC SPS25",n:"ALIMENTATION 18 VOLTS POUR COMMUTATEUR SATELLITE 8 POLARISAT",u:"Pièce",stock:false,fournisseur:"SATAIR",codeEsabora:"SAT"},
  {c:"Interphonie",s:"Comelit",r:"COT RCKPIC6L1020VP",n:"Kit de Démarrage VIGIK Plus Platine PIC 6 Plus - alim 4888C",u:"Pièce",stock:false,fournisseur:"COMELIT",codeEsabora:"COT"},
  {c:"Interphonie",s:"Comelit",r:"COT RCKPIC6L2020VP",n:"Kit de Démarrage VIGIK Plus Platine PIC 6 Plus - alim 1210A",u:"Pièce",stock:false,fournisseur:"COMELIT",codeEsabora:"COT"},
  {c:"Interphonie",s:"Comelit",r:"COT PIC6PL1020",n:"Platine PIC 6 Plus Light SBC1 avec 4680C - alim 4888C",u:"Pièce",stock:false,fournisseur:"COMELIT",codeEsabora:"COT"},
  {c:"Interphonie",s:"Comelit",r:"COT PIC6PL2020",n:"Platine PIC 6 Plus Light SBC2 avec 4681 - alim 1210A",u:"Pièce",stock:false,fournisseur:"COMELIT",codeEsabora:"COT"},
  {c:"Interphonie",s:"Comelit",r:"COT PICSWP6B1020",n:"Platine PIC Switch Plus Noir SBC1 avec 4680C - alim 4888C",u:"Pièce",stock:false,fournisseur:"COMELIT",codeEsabora:"COT"},
  {c:"Interphonie",s:"Comelit",r:"COT PICSWP6B2020",n:"Platine PIC Switch Plus Noir SBC2 avec 4681 - alim 1210A",u:"Pièce",stock:false,fournisseur:"COMELIT",codeEsabora:"COT"},
  {c:"Interphonie",s:"Comelit",r:"COT ACMRP",n:"Centrale 1 porte VIGIK PLUS",u:"Pièce",stock:false,fournisseur:"COMELIT",codeEsabora:"COT"},
  {c:"Interphonie",s:"Comelit",r:"COT RCKT25VP",n:"Kit de Démarrage VIGIK Plus Lecteur T25",u:"Pièce",stock:false,fournisseur:"COMELIT",codeEsabora:"COT"},
  {c:"Interphonie",s:"Comelit",r:"COT 4399",n:"Alimentation 12 Volts 4A",u:"Pièce",stock:false,fournisseur:"COMELIT",codeEsabora:"COT"},
  {c:"Interphonie",s:"Comelit",r:"COT BP/408L",n:"Bouton sonore + led monté sur façade inox",u:"Pièce",stock:false,fournisseur:"COMELIT",codeEsabora:"COT"},
  {c:"Interphonie",s:"Comelit",r:"COT 1210",n:"Alimentation 2 fils",u:"Pièce",stock:false,fournisseur:"COMELIT",codeEsabora:"COT"},
  {c:"Interphonie",s:"Comelit",r:"COT 1595",n:"TRANSFORMATEUR D'ALIMENTATION 33VCC",u:"Pièce",stock:false,fournisseur:"COMELIT",codeEsabora:"COT"},
  {c:"Interphonie",s:"Comelit",r:"COT 1214/2C",n:"BORNE DE DÉRIVATION DE SIGNAL",u:"Pièce",stock:false,fournisseur:"COMELIT",codeEsabora:"COT"},
  {c:"Interphonie",s:"Comelit",r:"COT CLE/B",n:"Clé résidant mifare Bleu",u:"Pièce",stock:false,fournisseur:"COMELIT",codeEsabora:"COT"},
  {c:"Interphonie",s:"Comelit",r:"COT CLE/J",n:"Clé résidant mifare Jaune",u:"Pièce",stock:false,fournisseur:"COMELIT",codeEsabora:"COT"},
  {c:"Interphonie",s:"Comelit",r:"COT CLE/O",n:"Clé résidant mifare Orange",u:"Pièce",stock:false,fournisseur:"COMELIT",codeEsabora:"COT"},
  {c:"Interphonie",s:"Comelit",r:"COT CLE/V",n:"Clé résidant mifare Vert",u:"Pièce",stock:false,fournisseur:"COMELIT",codeEsabora:"COT"},
  {c:"Interphonie",s:"Comelit",r:"COT 6710",n:"Etrier et borne de dérivation pour moniteur mini",u:"Pièce",stock:false,fournisseur:"COMELIT",codeEsabora:"COT"},
  {c:"Interphonie",s:"Comelit",r:"COT 6721W/BM",n:"Moniteur mini main libre BM blanc SB TOP",u:"Pièce",stock:false,fournisseur:"COMELIT",codeEsabora:"COT"},
  {c:"Interphonie",s:"Comelit",r:"COT PL6721BM",n:"MONITEUR PEOPLE MAINS LIBRES BM 4,3 pouces",u:"Pièce",stock:false,fournisseur:"COMELIT",codeEsabora:"COT"},
  {c:"Interphonie",s:"Comelit",r:"COT PL6731BM",n:"MONITEUR PEOPLE MAINS LIBRES BM 5 pouces",u:"Pièce",stock:false,fournisseur:"COMELIT",codeEsabora:"COT"},
  {c:"Interphonie",s:"Urmet",r:"URM D83/I",n:"PLATINE VIDEO À DEFILEMENT 2VOICE 2 LIGNES PERCAGE T25 - INO",u:"Pièce",stock:false,fournisseur:"SONEPAR",codeEsabora:"SONE"},
  {c:"Interphonie",s:"Urmet",r:"URM CVPLUS1P",n:"CENTRALE 1 PORTE CVPLUS1P, GESTION CONNECTEE OU L/E, JUSQU'A",u:"Pièce",stock:false,fournisseur:"SONEPAR",codeEsabora:"SONE"},
  {c:"Interphonie",s:"Urmet",r:"URM CVPLUS1P/SP",n:"CENTRALE 1P VIGIK+ LE/IP PERSONNALISE POUR SYSTEMES URMET",u:"Pièce",stock:false,fournisseur:"SONEPAR",codeEsabora:"SONE"},
  {c:"Interphonie",s:"Urmet",r:"URM KDATACVPLUS1P",n:"KIT COMPLET AVEC ALIM, CENTRALE CERTIFIEE VIGIK+, LECTEUR, M",u:"Pièce",stock:false,fournisseur:"SONEPAR",codeEsabora:"SONE"},
  {c:"Interphonie",s:"Urmet",r:"URM ANTGPRS3G4G",n:"ANTENNE URMET POUR DEPORTER LA RECEPTION DU MODEM GPRS, 3G,",u:"Pièce",stock:false,fournisseur:"SONEPAR",codeEsabora:"SONE"},
  {c:"Interphonie",s:"Urmet",r:"URM 1083/75",n:"2VOICE INTERFACE 4P 4C POUR SYSTEMES URMET",u:"Pièce",stock:false,fournisseur:"SONEPAR",codeEsabora:"SONE"},
  {c:"Interphonie",s:"Urmet",r:"URM 1083/53",n:"INTERFACE 2 PLATINES 2 COLONNES 2VOICE 4 DIN",u:"Pièce",stock:false,fournisseur:"SONEPAR",codeEsabora:"SONE"},
  {c:"Interphonie",s:"Urmet",r:"URM 1083/55",n:"DERIVATEUR VIDEO 4 SORTIES 2VOICE POUR SYSTEMES URMET",u:"Pièce",stock:false,fournisseur:"SONEPAR",codeEsabora:"SONE"},
  {c:"Interphonie",s:"Urmet",r:"URM AL12/2DIN",n:"ALIM REGULEE 12VCC 2A, REGLABLE 12-14V, 3 MODULES, VOYANT SE",u:"Pièce",stock:false,fournisseur:"SONEPAR",codeEsabora:"SONE"},
  {c:"Interphonie",s:"Urmet",r:"URM 1760/6",n:"MONITEUR D'INTERPHONIE MAIN-LIBRE VOG5 AVEC ÉCRAN 5' COMPATI",u:"Pièce",stock:false,fournisseur:"SONEPAR",codeEsabora:"SONE"},
  {c:"Lustrerie",s:"Ampoule Led E27",r:"BLD BL06092002",n:"BULB LAMPE A60-E27-9W-4000K-NON DIM",u:"Pièce",stock:true,fournisseur:"BE LED",codeEsabora:"BLD"},
  {c:"Lustrerie",s:"Ampoule Led E27",r:"BLD BL06092001",n:"BULB LAMPE A60-E27-9W-3000K NON DIM",u:"Pièce",stock:true,fournisseur:"BE LED",codeEsabora:"BLD"},
  {c:"Lustrerie",s:"Ampoule Led Gu10",r:"SON LAPAR01",n:"LAMPE LED GU10 4.9W 535LM 3000K x5p (BLANC CHAUD)",u:"Pièce",stock:false,fournisseur:"SONEPAR",codeEsabora:"SONE"},
  {c:"Lustrerie",s:"Ampoule Led Gu10",r:"SON LAPAR02",n:"LAMPE LED GU10  4.9W 535LM 4000K x5p (BLANC FROID)",u:"Pièce",stock:false,fournisseur:"SONEPAR",codeEsabora:"SONE"},
  {c:"Lustrerie",s:"Ampoule Led Gu10",r:"SON LAPAR03",n:"LAMPE LED GU10 DIM 5.7W 540LM 3000K x5p (BLANC CHAUD DIM)",u:"Pièce",stock:false,fournisseur:"SONEPAR",codeEsabora:"SONE"},
  {c:"Lustrerie",s:"Ampoule Led Gu10",r:"SON LAPAR04",n:"LAMPE LED GU10 DIM 5.7W 540LM 4000K x5p (BLANC FROID DIM)",u:"Pièce",stock:false,fournisseur:"SONEPAR",codeEsabora:"SONE"},
  {c:"Lustrerie",s:"Ampoule Led Gu10",r:"RES 931015",n:"AMP LED 7W 756lm GU10 3000K",u:"Pièce",stock:false,fournisseur:"RESISTEX",codeEsabora:"RES"},
  {c:"Lustrerie",s:"Ampoule Led Gu10",r:"RES 931016",n:"AMP LED 7W 742lm GU10 4000K",u:"Pièce",stock:false,fournisseur:"RESISTEX",codeEsabora:"RES"},
  {c:"Lustrerie",s:"Fluo Led",r:"RES 607000",n:"SIMPLY 35W 4000K 4196lm",u:"Pièce",stock:true,fournisseur:"RESISTEX",codeEsabora:"RES"},
  {c:"Lustrerie",s:"Fluo Led",r:"RES 607001",n:"SIMPLY 50W 4000K 5517lm",u:"Pièce",stock:true,fournisseur:"RESISTEX",codeEsabora:"RES"},
  {c:"Lustrerie",s:"Local Technique / Sas Sous-sol",r:"RES 830000",n:"HUBO 18W CCT 4000K 1678lm",u:"Pièce",stock:true,fournisseur:"RESISTEX",codeEsabora:"RES"},
  {c:"Lustrerie",s:"Local Technique / Sas Sous-sol",r:"RES 830001",n:"HUBO 18W DET CCT 4000K 1678lm",u:"Pièce",stock:true,fournisseur:"RESISTEX",codeEsabora:"RES"},
  {c:"Lustrerie",s:"Escalier",r:"RES 850700",n:"KOMET 20W 4000K BLANC 2193lm",u:"Pièce",stock:false,fournisseur:"RESISTEX",codeEsabora:"RES"},
  {c:"Lustrerie",s:"Escalier",r:"RES 850701",n:"KOMET 20W HF 4000K BLANC 2193lm",u:"Pièce",stock:false,fournisseur:"RESISTEX",codeEsabora:"RES"},
  {c:"Lustrerie",s:"Escalier",r:"BLD BL12256507",n:"FOG 360-24W-3000K-IP66-DETECT",u:"Pièce",stock:false,fournisseur:"BE LED",codeEsabora:"BLD"},
  {c:"Lustrerie",s:"Escalier",r:"BLD BL12256504",n:"TF100-FOG ASYM SENSOR-25W-IP66-WHITE-3000K-850°",u:"Pièce",stock:false,fournisseur:"BE LED",codeEsabora:"BLD"},
  {c:"Lustrerie",s:"Circulation",r:"RES 759405",n:"MUSE ROND 18W 2231LM CCT",u:"Pièce",stock:false,fournisseur:"RESISTEX",codeEsabora:"RES"},
  {c:"Lustrerie",s:"Circulation",r:"RES 759407",n:"MUSE CARRE 18W 2231LM CCT",u:"Pièce",stock:false,fournisseur:"RESISTEX",codeEsabora:"RES"},
  {c:"Lustrerie",s:"Circulation",r:"RES 946215",n:"BALDER 500 DOWN 3000K ANTHRA",u:"Pièce",stock:false,fournisseur:"RESISTEX",codeEsabora:"RES"},
  {c:"Lustrerie",s:"Spot Led",r:"RES 963210",n:"MIKS 598lm CCT ANNEAU FIXE ROND BLANC",u:"Pièce",stock:false,fournisseur:"RESISTEX",codeEsabora:"RES"},
  {c:"Lustrerie",s:"Spot Led",r:"RES 963240",n:"MIKS 1185lm CCT ANNEAU FIXE ROND BLANC",u:"Pièce",stock:false,fournisseur:"RESISTEX",codeEsabora:"RES"},
  {c:"Lustrerie",s:"Spot Led",r:"RES 963222",n:"MIKS 506lm CCT B.LUM RD/RD BLANC REFLECTEUR BLANC",u:"Pièce",stock:false,fournisseur:"RESISTEX",codeEsabora:"RES"},
  {c:"Lustrerie",s:"Spot Led",r:"RES 9633252",n:"MIKS 1043lm CCT B.LUM RD/RD BLANC REFLECTEUR BLANC",u:"Pièce",stock:false,fournisseur:"RESISTEX",codeEsabora:"RES"},
  {c:"Lustrerie",s:"Spot Led",r:"RES 963226",n:"MIKS 412lm CCT B.LUM RD/RD NOIR REFLECTEUR NOIR",u:"Pièce",stock:false,fournisseur:"RESISTEX",codeEsabora:"RES"},
  {c:"Lustrerie",s:"Exterieur",r:"NOL 623180",n:"Bassi hub. GRAPH. E27/CFL",u:"Pièce",stock:false,fournisseur:"SONEPAR",codeEsabora:"SONE"},
  {c:"Lustrerie",s:"Exterieur",r:"RES 946532",n:"MARKIZ E27 NOIR + LAMPE E27",u:"Pièce",stock:false,fournisseur:"RESISTEX",codeEsabora:"RES"},
  {c:"Lustrerie",s:"Exterieur",r:"RES 946533",n:"MARKIZ E27 BLANC + LAMPE E27",u:"Pièce",stock:false,fournisseur:"RESISTEX",codeEsabora:"RES"},
  {c:"Lustrerie",s:"Exterieur",r:"RES 946610",n:"LETARI 8W 3000K NR",u:"Pièce",stock:false,fournisseur:"RESISTEX",codeEsabora:"RES"},
  {c:"Quincaillerie",s:"Scotch",r:"WUR 0992500999",n:"RUBAN ORANGE PE CHANTIER 33M",u:"Pièce",stock:true,fournisseur:"WURTH",codeEsabora:"WUR"},
  {c:"Quincaillerie",s:"Scotch",r:"VIN 2000083",n:"ADHESIF PLASTIFIE 38MMX33M ROUGE",u:"Pièce",stock:true,fournisseur:"VINAY",codeEsabora:"VIN"},
  {c:"Quincaillerie",s:"Scotch Lock",r:"WUR 0556010",n:"CONNECTEUR BASSE TENSION 2 ENTREES J",u:"Pièce",stock:true,fournisseur:"WURTH",codeEsabora:"WUR"},
  {c:"Quincaillerie",s:"Scotch Lock",r:"WUR 0556012",n:"CONNECTEUR BASSE TENSION 3 ENTREES R",u:"Pièce",stock:true,fournisseur:"WURTH",codeEsabora:"WUR"},
  {c:"Quincaillerie",s:"Wago",r:"WUR 0556500300",n:"CONNECTEUR TRANS. REDUIT 3 ENTREES",u:"Pièce",stock:true,fournisseur:"WURTH",codeEsabora:"WUR"},
  {c:"Quincaillerie",s:"Wago",r:"WUR 0556500500",n:"CONNECTEUR TRANS. REDUIT 5 ENTREES",u:"Pièce",stock:true,fournisseur:"WURTH",codeEsabora:"WUR"},
  {c:"Quincaillerie",s:"Wago",r:"BLI 460180",n:"CONNECTEUR TRANS. REDUIT 8 ENTREES",u:"Pièce",stock:true,fournisseur:"SONEPAR",codeEsabora:"SONE"},
  {c:"Quincaillerie",s:"Wago Souple Rigide",r:"BLI 401022",n:"Borne luminaire 1 fil sple - 2 fils rigides 2,5mm²",u:"Pièce",stock:true,fournisseur:"SONEPAR",codeEsabora:"SONE"},
  {c:"Quincaillerie",s:"Wago Souple Rigide",r:"WUR 05561183",n:"CONN. MINI SPLE/RGDE 3E.KOMPAKT PLUS",u:"Pièce",stock:true,fournisseur:"WURTH",codeEsabora:"WUR"},
  {c:"Quincaillerie",s:"Sucre",r:"WUR 0556200102",n:"BARRETTE DE CONNEX. NOIR 2.5-10 MM²",u:"Pièce",stock:true,fournisseur:"WURTH",codeEsabora:"WUR"},
  {c:"Quincaillerie",s:"Sucre",r:"WUR 0556200103",n:"BARRETTE DE CONNEX. NOIR 16 MM²",u:"Pièce",stock:true,fournisseur:"WURTH",codeEsabora:"WUR"},
  {c:"Quincaillerie",s:"Sucre",r:"WUR 0556200120",n:"BARRETTE DE CONNEX. NOIR 25 MM²",u:"Pièce",stock:true,fournisseur:"WURTH",codeEsabora:"WUR"},
  {c:"Quincaillerie",s:"Collier",r:"WUR 0502109260",n:"COLSONE 260 mm",u:"Pièce",stock:true,fournisseur:"WURTH",codeEsabora:"WUR"},
  {c:"Quincaillerie",s:"Collier",r:"WUR 0502109360",n:"COLSONE 360 mm",u:"Pièce",stock:true,fournisseur:"WURTH",codeEsabora:"WUR"},
  {c:"Quincaillerie",s:"Collier",r:"WUR 0502131",n:"FRETTE 200mm",u:"Pièce",stock:true,fournisseur:"WURTH",codeEsabora:"WUR"},
  {c:"Quincaillerie",s:"Collier",r:"WUR 0502151",n:"FRETTE 280mm",u:"Pièce",stock:true,fournisseur:"WURTH",codeEsabora:"WUR"},
  {c:"Quincaillerie",s:"Embase",r:"WUR 050336537",n:"EMBASE A CHEVILLE STANDARD",u:"Pièce",stock:true,fournisseur:"WURTH",codeEsabora:"WUR"},
  {c:"Quincaillerie",s:"Embase",r:"WUR 0971510032",n:"FIXE-TUBES VARIABLE DIAM. 15 A 32 MM",u:"Pièce",stock:true,fournisseur:"WURTH",codeEsabora:"WUR"},
  {c:"Quincaillerie",s:"Mousse / Pistolet",r:"WUR 08921521",n:"MOUSSE MONTAGE PU 750ML - PISTOLABLE",u:"Pièce",stock:true,fournisseur:"WURTH",codeEsabora:"WUR"},
  {c:"Quincaillerie",s:"Mousse / Pistolet",r:"WUR 0892160",n:"NETTOYANT PISTOLET MOUSSE MONT.500ML",u:"Pièce",stock:true,fournisseur:"WURTH",codeEsabora:"WUR"},
  {c:"Quincaillerie",s:"Mousse / Pistolet",r:"VIN 0104531",n:"PISTOLET BOMBE MOUSSE POLYURET OX",u:"Pièce",stock:true,fournisseur:"VINAY",codeEsabora:"VIN"},
  {c:"Quincaillerie",s:"Bombe De Traçage",r:"WUR 08921751",n:"TRACEUR DE CHANTIER BLANC",u:"Pièce",stock:true,fournisseur:"WURTH",codeEsabora:"WUR"},
  {c:"Quincaillerie",s:"Bombe De Traçage",r:"WUR 08921753",n:"TRACEUR DE CHANTIER ROUGE FLUO",u:"Pièce",stock:true,fournisseur:"WURTH",codeEsabora:"WUR"},
  {c:"Quincaillerie",s:"Acrylique",r:"WUR 0892165001",n:"MASTIC ACRYLIQUE STANDARD310ML BLANC",u:"Pièce",stock:true,fournisseur:"WURTH",codeEsabora:"WUR"},
  {c:"Quincaillerie",s:"Silicone",r:"WUR 089285732",n:"A8 PRO SILICONE NEUTRE TRANS 310ML",u:"Pièce",stock:true,fournisseur:"WURTH",codeEsabora:"WUR"},
  {c:"Quincaillerie",s:"Vis",r:"WUR 019864535",n:"VIS WUPO TF POZI AC ZI 4,5X35",u:"Pièce",stock:true,fournisseur:"WURTH",codeEsabora:"WUR"},
  {c:"Quincaillerie",s:"Vis",r:"WUR 01986640",n:"VIS WUPO TF POZI AC ZI 6X40",u:"Pièce",stock:true,fournisseur:"WURTH",codeEsabora:"WUR"},
  {c:"Quincaillerie",s:"Cheville",r:"WUR 090320630",n:"CHEVILLE Ø6",u:"Pièce",stock:true,fournisseur:"WURTH",codeEsabora:"WUR"},
  {c:"Quincaillerie",s:"Cheville",r:"WUR 090320840",n:"CHEVILLE Ø8",u:"Pièce",stock:true,fournisseur:"WURTH",codeEsabora:"WUR"},
  {c:"Quincaillerie",s:"Cheville",r:"WUR 0903300301",n:"CHEVILLE ARPON Ø6",u:"Pièce",stock:true,fournisseur:"WURTH",codeEsabora:"WUR"},
  {c:"Quincaillerie",s:"Cheville",r:"WUR 0903300302",n:"CHEVILLE ARPON Ø8",u:"Pièce",stock:true,fournisseur:"WURTH",codeEsabora:"WUR"},
  {c:"Quincaillerie",s:"Ecrou / Rondelle",r:"WUR 03178",n:"ECROU M8",u:"Pièce",stock:true,fournisseur:"WURTH",codeEsabora:"WUR"},
  {c:"Quincaillerie",s:"Ecrou / Rondelle",r:"WUR 0411625",n:"RONDELLE M6",u:"Pièce",stock:true,fournisseur:"WURTH",codeEsabora:"WUR"},
  {c:"Quincaillerie",s:"Ecrou / Rondelle",r:"WUR 0411825",n:"RONDELLE M8",u:"Pièce",stock:true,fournisseur:"WURTH",codeEsabora:"WUR"},
  {c:"Quincaillerie",s:"Tifix",r:"WUR 5932008075",n:"TI-FIX 75 mm",u:"Pièce",stock:true,fournisseur:"WURTH",codeEsabora:"WUR"},
  {c:"Quincaillerie",s:"Tifix",r:"WUR 0904520804",n:"TI-FIX 165 mm",u:"Pièce",stock:true,fournisseur:"WURTH",codeEsabora:"WUR"},
  {c:"Quincaillerie",s:"Cheville Molly",r:"WUR 0903811634",n:"CHEV. PAROIS CREUSES 6X34 AVEC VIS",u:"Pièce",stock:true,fournisseur:"WURTH",codeEsabora:"WUR"},
  {c:"Quincaillerie",s:"Cheville Molly",r:"WUR 0903811675",n:"CHEV. PAROIS CREUSES 6X75 AVEC VIS",u:"Pièce",stock:true,fournisseur:"WURTH",codeEsabora:"WUR"},
  {c:"Quincaillerie",s:"Driva",r:"WUR 0903252",n:"CHEV-METAL-AUTOPERC-(W-GS/Z)-ZD-14,5X33",u:"Pièce",stock:true,fournisseur:"WURTH",codeEsabora:"WUR"},
  {c:"Quincaillerie",s:"Cheville Isolant Exterieur",r:"WUR 59035005",n:"CHEVILLE POUR ISOLATION SHARK ISO 50",u:"Pièce",stock:true,fournisseur:"WURTH",codeEsabora:"WUR"},
  {c:"Quincaillerie",s:"Foret",r:"WUR 0648556011",n:"FORET Ø6 COURT",u:"Pièce",stock:true,fournisseur:"WURTH",codeEsabora:"WUR"},
  {c:"Quincaillerie",s:"Foret",r:"WUR 0648556016",n:"FORET Ø6 LONG",u:"Pièce",stock:true,fournisseur:"WURTH",codeEsabora:"WUR"},
  {c:"Quincaillerie",s:"Foret",r:"WUR 0648558011",n:"FORET Ø8 COURT",u:"Pièce",stock:true,fournisseur:"WURTH",codeEsabora:"WUR"},
  {c:"Quincaillerie",s:"Foret",r:"WUR 0648558016",n:"FORET Ø8 LONG",u:"Pièce",stock:true,fournisseur:"WURTH",codeEsabora:"WUR"},
  {c:"Outillage",s:"Scie Cloche / Embout / Malaxeur",r:"VIN 2002057",n:"ADAPTATEUR POWER CHANGE PLUS QUEUE 6 PANS 8.7MM",u:"Pièce",stock:false,fournisseur:"VINAY",codeEsabora:"VIN"},
  {c:"Outillage",s:"Scie Cloche / Embout / Malaxeur",r:"VIN 2002301",n:"SCIE TREPAN 68MM POWERCHANGE",u:"Pièce",stock:false,fournisseur:"VINAY",codeEsabora:"VIN"},
  {c:"Outillage",s:"Scie Cloche / Embout / Malaxeur",r:"VIN 0421671",n:"SCIE TREPAN 86MM POWERCHANGE",u:"Pièce",stock:false,fournisseur:"VINAY",codeEsabora:"VIN"},
  {c:"Outillage",s:"Scie Cloche / Embout / Malaxeur",r:"VIN 2002054",n:"FORET DE CENTRAGE PLUS HSS-G Ø7.15X85MM",u:"Pièce",stock:false,fournisseur:"VINAY",codeEsabora:"VIN"},
  {c:"Outillage",s:"Scie Cloche / Embout / Malaxeur",r:"VIN421822",n:"MANDRIN AUTOMATIQUE + ADAPTATEUR SDS+",u:"Pièce",stock:false,fournisseur:"VINAY",codeEsabora:"VIN"},
  {c:"Outillage",s:"Scie Cloche / Embout / Malaxeur",r:"VIN 421370",n:"PORTE EMBOUT MAGNETIQUE BOSCH",u:"Pièce",stock:false,fournisseur:"VINAY",codeEsabora:"VIN"},
  {c:"Outillage",s:"Scie Cloche / Embout / Malaxeur",r:"VIN 423492",n:"TIGE MALAXAGE SVEDEN 100X500",u:"Pièce",stock:false,fournisseur:"VINAY",codeEsabora:"VIN"},
  {c:"Outillage",s:"Trepant",r:"VIN 0424089",n:"FORET DE CENTRAGE SDS+ PLUS-5 S4L",u:"Pièce",stock:false,fournisseur:"VINAY",codeEsabora:"VIN"},
  {c:"Outillage",s:"Trepant",r:"VIN423848",n:"PORTE OUTIL COURONNE TREPAN BOSCH",u:"Pièce",stock:false,fournisseur:"VINAY",codeEsabora:"VIN"},
  {c:"Outillage",s:"Trepant",r:"VIN423846",n:"TREPAN BOSCH 68",u:"Pièce",stock:false,fournisseur:"VINAY",codeEsabora:"VIN"},
  {c:"Outillage",s:"Trepant",r:"VIN423846",n:"TREPAN BOSCH 90",u:"Pièce",stock:false,fournisseur:"VINAY",codeEsabora:"VIN"},
  {c:"Outillage",s:"Equipement Monteur",r:"VIN 266535",n:"SEAU PLAST NOIRE 11L  310183",u:"Pièce",stock:false,fournisseur:"VINAY",codeEsabora:"VIN"},
  {c:"Outillage",s:"Equipement Monteur",r:"VIN 265318",n:"TENAILLE RUSSE 220MM KNIPEX",u:"Pièce",stock:false,fournisseur:"VINAY",codeEsabora:"VIN"},
  {c:"Outillage",s:"Equipement Monteur",r:"VIN 265160",n:"PINCE BECS MI-RONDS DR 200",u:"Pièce",stock:false,fournisseur:"VINAY",codeEsabora:"VIN"},
  {c:"Outillage",s:"Equipement Monteur",r:"VIN 265656",n:"POCHE CLOUS 8 POCHES TOILE",u:"Pièce",stock:false,fournisseur:"VINAY",codeEsabora:"VIN"},
  {c:"Outillage",s:"Equipement Monteur",r:"VIN 266176",n:"MASSETTE 1.20KG LEBOR M.BOIS",u:"Pièce",stock:false,fournisseur:"VINAY",codeEsabora:"VIN"},
  {c:"Outillage",s:"Equipement Monteur",r:"VIN 268413",n:"BURIN DE CARROSSIER 235MM EXTRA PLAT",u:"Pièce",stock:false,fournisseur:"VINAY",codeEsabora:"VIN"},
  {c:"Outillage",s:"Equipement Monteur",r:"VIN 269280",n:"BROCHE MACON 16X300 MERCIER",u:"Pièce",stock:false,fournisseur:"VINAY",codeEsabora:"VIN"},
  {c:"Outillage",s:"Equipement Monteur",r:"VIN 265849",n:"MARTEAU ELECTR. 18MM  GRAPHITE 200GR",u:"Pièce",stock:false,fournisseur:"VINAY",codeEsabora:"VIN"},
  {c:"Outillage",s:"Equipement Monteur",r:"VIN 265041",n:"COUTEAU CARBONE OPINEL N°10V",u:"Pièce",stock:false,fournisseur:"VINAY",codeEsabora:"VIN"},
  {c:"Outillage",s:"Equipement Monteur",r:"VIN 0269467",n:"COUTEAU AVEC SIFFLET OUTDOOR",u:"Pièce",stock:false,fournisseur:"VINAY",codeEsabora:"VIN"},
  {c:"Outillage",s:"Equipement Monteur",r:"VIN 264440",n:"NIVEAU COMPOSIT 40CM STANLEY",u:"Pièce",stock:false,fournisseur:"VINAY",codeEsabora:"VIN"},
  {c:"Outillage",s:"Equipement Monteur",r:"VIN 268884",n:"MESURE  5MX32MM MAGNET FATMAX BLADE ARMOR  STANLEY",u:"Pièce",stock:false,fournisseur:"VINAY",codeEsabora:"VIN"},
  {c:"Outillage",s:"Equipement Monteur",r:"VIN 268885",n:"MESURE 8MX32MM MAGNET FATMAX BLADE ARMOR STANLEY",u:"Pièce",stock:false,fournisseur:"VINAY",codeEsabora:"VIN"},
  {c:"Outillage",s:"Equipement Monteur",r:"VIN 266680",n:"TOURNEVIS JEU DE 6 ISOLE STAN",u:"Pièce",stock:false,fournisseur:"VINAY",codeEsabora:"VIN"},
  {c:"Outillage",s:"Equipement Monteur",r:"VIN 267366",n:"TOURNEVIS PROTWIST PH1 VE 1000V",u:"Pièce",stock:false,fournisseur:"VINAY",codeEsabora:"VIN"},
  {c:"Outillage",s:"Equipement Monteur",r:"VIN 267366",n:"TOURNEVIS PROTWIST 2X75VE 1000V",u:"Pièce",stock:false,fournisseur:"VINAY",codeEsabora:"VIN"},
  {c:"Outillage",s:"Equipement Monteur",r:"VIN 268501",n:"TOURNEVIS PROTWIST 4X100VE 1000V",u:"Pièce",stock:false,fournisseur:"VINAY",codeEsabora:"VIN"},
  {c:"Outillage",s:"Equipement Monteur",r:"VIN 268462",n:"TOURNEVIS PROTWIST FENT FORGEE 6.5X150",u:"Pièce",stock:false,fournisseur:"VINAY",codeEsabora:"VIN"},
  {c:"Outillage",s:"Equipement Monteur",r:"LEG 031996",n:"PINCE POUR COLLIER COLSON",u:"Pièce",stock:false,fournisseur:"SONEPAR",codeEsabora:"SONE"},
  {c:"Outillage",s:"Equipement Monteur",r:"AGI 221009",n:"PINCE DENUDE 1,5 / 2,5",u:"Pièce",stock:false,fournisseur:"SONEPAR",codeEsabora:"SONE"},
  {c:"Outillage",s:"Equipement Monteur",r:"AGI 424023",n:"COUPE CABLES",u:"Pièce",stock:false,fournisseur:"SONEPAR",codeEsabora:"SONE"},
  {c:"Outillage",s:"Equipement Monteur",r:"VIN 267416",n:"CLE MIXTE 42 10  BETA France",u:"Pièce",stock:false,fournisseur:"VINAY",codeEsabora:"VIN"},
  {c:"Outillage",s:"Equipement Monteur",r:"VIN 267419",n:"CLE MIXTE 42 13  BETA France",u:"Pièce",stock:false,fournisseur:"VINAY",codeEsabora:"VIN"},
  {c:"Outillage",s:"Equipement Monteur",r:"VIN 267467",n:"CLE A PIPE DEBOUCHEE 6X6PANS 933 10X10 BETA France",u:"Pièce",stock:false,fournisseur:"VINAY",codeEsabora:"VIN"},
  {c:"Outillage",s:"Equipement Monteur",r:"VIN267470",n:"CLE A PIPE DEBOUCHEE 6X6PANS 933 13X13 BETA France",u:"Pièce",stock:false,fournisseur:"VINAY",codeEsabora:"VIN"},
  {c:"Outillage",s:"Equipement Monteur",r:"VIN 267323",n:"CLE BTR JEU DE 8 1.5A8 MONTURE STANLEY",u:"Pièce",stock:false,fournisseur:"VINAY",codeEsabora:"VIN"},
  {c:"Outillage",s:"Equipement Monteur",r:"VIN 264977",n:"SCIE A METAUX URKO",u:"Pièce",stock:false,fournisseur:"VINAY",codeEsabora:"VIN"},
  {c:"Outillage",s:"Equipement Monteur",r:"VIN 264987",n:"SCIE EGOINE 152MM PANN PLATRE",u:"Pièce",stock:false,fournisseur:"VINAY",codeEsabora:"VIN"},
  {c:"Outillage",s:"Platre",r:"VIN 265987",n:"TRUELLE CARREE 16 M PLASTIQUE",u:"Pièce",stock:false,fournisseur:"VINAY",codeEsabora:"VIN"},
  {c:"Outillage",s:"Platre",r:"VIN 268339",n:"PLATOIR ACIER INOX 28X12",u:"Pièce",stock:false,fournisseur:"VINAY",codeEsabora:"VIN"},
  {c:"Outillage",s:"Platre",r:"VIN 520144",n:"COUTEAU A ENDUIRE INOX 20CM",u:"Pièce",stock:false,fournisseur:"VINAY",codeEsabora:"VIN"},
  {c:"Outillage",s:"Platre",r:"VIN 269525",n:"AUGE PLASTIQUE NOIRE N.1 25L  RUBI 88771",u:"Pièce",stock:false,fournisseur:"VINAY",codeEsabora:"VIN"},
  {c:"Outillage",s:"Divers",r:"VIN 204290",n:"ESCABEAU ALU COFAQ 3 MARCHES",u:"Pièce",stock:false,fournisseur:"VINAY",codeEsabora:"VIN"},
  {c:"Outillage",s:"Divers",r:"VIN 204291",n:"ESCABEAU ALU COFAQ 4 MARCHES",u:"Pièce",stock:false,fournisseur:"VINAY",codeEsabora:"VIN"},
  {c:"Outillage",s:"Divers",r:"VIN 480044",n:"ENROULEUR 25M 3X1.5",u:"Pièce",stock:false,fournisseur:"VINAY",codeEsabora:"VIN"},
  {c:"Outillage",s:"Divers",r:"VIN 266240",n:"COUPE BOULON SAM 1/600MM L95",u:"Pièce",stock:false,fournisseur:"VINAY",codeEsabora:"VIN"},
  {c:"Outillage",s:"Divers",r:"VIN 284168",n:"HOUSSE PROTEGE PLAN 150X100",u:"Pièce",stock:false,fournisseur:"VINAY",codeEsabora:"VIN"},
  {c:"Outillage",s:"Divers",r:"VIN 144404",n:"FIL DE FER N10 SEAU 20KG EN PETITE BOBINE",u:"Pièce",stock:false,fournisseur:"VINAY",codeEsabora:"VIN"},
  {c:"Outillage",s:"Divers",r:"VIN 264345",n:"CORDEX PVC RONDO 30M",u:"Pièce",stock:false,fournisseur:"VINAY",codeEsabora:"VIN"},
  {c:"Outillage",s:"Divers",r:"VIN 264291",n:"BIBERON POUDRE BLEU 400G",u:"Pièce",stock:false,fournisseur:"VINAY",codeEsabora:"VIN"},
  {c:"Outillage",s:"Divers",r:"VIN 264307",n:"CRAYON MACON LYRA",u:"Pièce",stock:false,fournisseur:"VINAY",codeEsabora:"VIN"},
  {c:"Outillage",s:"Divers",r:"VIN 1060399",n:"CRAYON GRAPHITE PICA DRY WILMART",u:"Pièce",stock:false,fournisseur:"VINAY",codeEsabora:"VIN"},
  {c:"Outillage",s:"Divers",r:"VIN 1100007",n:"MINE RECHARGE PICA DRY 10 UNI WILMART",u:"Pièce",stock:false,fournisseur:"VINAY",codeEsabora:"VIN"},
  {c:"Outillage",s:"Divers",r:"VIN 264987",n:"SCIE EGOINE 152MM PANN PLATRE",u:"Pièce",stock:false,fournisseur:"VINAY",codeEsabora:"VIN"},
  {c:"Outillage",s:"Divers",r:"BIZ 700231",n:"GEL LUBRIFIANT POUR CABLES ET FILS BIZ'LUB",u:"Pièce",stock:false,fournisseur:"SONEPAR",codeEsabora:"SONE"},
  {c:"Outillage",s:"Divers",r:"CAP 599200",n:"CAPRIGEL GTI 1L POUR TOUS TYPES DE CABLES",u:"Pièce",stock:false,fournisseur:"SONEPAR",codeEsabora:"SONE"},
  {c:"Outillage",s:"Divers",r:"AGI 398443",n:"Aiguille en nylon de 25 m",u:"Pièce",stock:false,fournisseur:"SONEPAR",codeEsabora:"SONE"},
  {c:"Outillage",s:"Divers",r:"AGI 398445",n:"Aiguille en nylon de 30 m",u:"Pièce",stock:false,fournisseur:"SONEPAR",codeEsabora:"SONE"},
  {c:"Outillage",s:"Divers",r:"AGI 398425",n:"Tête de guidage flexible M4",u:"Pièce",stock:false,fournisseur:"SONEPAR",codeEsabora:"SONE"},
  {c:"Outillage",s:"Divers",r:"AGI 398429",n:"Oeillet de tirage M4",u:"Pièce",stock:false,fournisseur:"SONEPAR",codeEsabora:"SONE"},
  {c:"Outillage",s:"Divers",r:"AGI 398431",n:"Chaussette de tirage pourcâbles de ø 4 à 6 mm M4",u:"Pièce",stock:false,fournisseur:"SONEPAR",codeEsabora:"SONE"},
  {c:"Outillage",s:"Divers",r:"AGI 398419",n:"Tête de guidage flexible à sertir",u:"Pièce",stock:false,fournisseur:"SONEPAR",codeEsabora:"SONE"},
  {c:"Outillage",s:"Divers",r:"AGI 398421",n:"Oeillet de tirage à sertir",u:"Pièce",stock:false,fournisseur:"SONEPAR",codeEsabora:"SONE"},
  {c:"Outillage",s:"Divers",r:"AGI 398607",n:"Pince à sertir",u:"Pièce",stock:false,fournisseur:"SONEPAR",codeEsabora:"SONE"},
  {c:"Vêtements de travail",s:"Pantalon",r:"VIN 360505",n:"PANTALON MULTIPOCHES NOIR     T38",u:"Pièce",stock:true,fournisseur:"VINAY",codeEsabora:"VIN"},
  {c:"Vêtements de travail",s:"Pantalon",r:"VIN 361084",n:"PANTALON MULTIPOCHES NOIR     T40",u:"Pièce",stock:true,fournisseur:"VINAY",codeEsabora:"VIN"},
  {c:"Vêtements de travail",s:"Pantalon",r:"VIN 361085",n:"PANTALON MULTIPOCHES NOIR     T42",u:"Pièce",stock:true,fournisseur:"VINAY",codeEsabora:"VIN"},
  {c:"Vêtements de travail",s:"Pantalon",r:"VIN 361086",n:"PANTALON MULTIPOCHES NOIR     T44",u:"Pièce",stock:true,fournisseur:"VINAY",codeEsabora:"VIN"},
  {c:"Vêtements de travail",s:"Pantalon",r:"VIN 361087",n:"PANTALON MULTIPOCHES NOIR     T46",u:"Pièce",stock:true,fournisseur:"VINAY",codeEsabora:"VIN"},
  {c:"Vêtements de travail",s:"T-shirt",r:"TEX T-SHIRT NOIR M",n:"T-SHIRT NOIR TAILLE M",u:"Pièce",stock:true,fournisseur:"EPJ",codeEsabora:"EPJ"},
  {c:"Vêtements de travail",s:"T-shirt",r:"TEX T-SHIRT NOIR L",n:"T-SHIRT NOIR TAILLE L",u:"Pièce",stock:true,fournisseur:"EPJ",codeEsabora:"EPJ"},
  {c:"Vêtements de travail",s:"T-shirt",r:"TEX T-SHIRT NOIR XL",n:"T-SHIRT NOIR TAILLE XL",u:"Pièce",stock:true,fournisseur:"EPJ",codeEsabora:"EPJ"},
  {c:"Vêtements de travail",s:"T-shirt",r:"TEX T-SHIRT BLEU M",n:"T-SHIRT BLEU TAILLE M",u:"Pièce",stock:true,fournisseur:"EPJ",codeEsabora:"EPJ"},
  {c:"Vêtements de travail",s:"T-shirt",r:"TEX T-SHIRT BLEU L",n:"T-SHIRT BLEU TAILLE L",u:"Pièce",stock:true,fournisseur:"EPJ",codeEsabora:"EPJ"},
  {c:"Vêtements de travail",s:"T-shirt",r:"TEX T-SHIRT BLEU XL",n:"T-SHIRT BLEU TAILLE XL",u:"Pièce",stock:true,fournisseur:"EPJ",codeEsabora:"EPJ"},
  {c:"Vêtements de travail",s:"T-shirt",r:"TEX T-SHIRT ORANGE M",n:"T-SHIRT ORANGE TAILLE M",u:"Pièce",stock:true,fournisseur:"EPJ",codeEsabora:"EPJ"},
  {c:"Vêtements de travail",s:"T-shirt",r:"TEX T-SHIRT ORANGE L",n:"T-SHIRT ORANGE TAILLE L",u:"Pièce",stock:true,fournisseur:"EPJ",codeEsabora:"EPJ"},
  {c:"Vêtements de travail",s:"T-shirt",r:"TEX T-SHIRT ORANGE XL",n:"T-SHIRT ORANGE TAILLE XL",u:"Pièce",stock:true,fournisseur:"EPJ",codeEsabora:"EPJ"},
  {c:"Vêtements de travail",s:"Sweet A Capuche",r:"TEX SWEET A CAPUCHE M",n:"SWEET A CAPUCHE TAILLE M",u:"Pièce",stock:true,fournisseur:"EPJ",codeEsabora:"EPJ"},
  {c:"Vêtements de travail",s:"Sweet A Capuche",r:"TEX SWEET A CAPUCHE L",n:"SWEET A CAPUCHE TAILLE L",u:"Pièce",stock:true,fournisseur:"EPJ",codeEsabora:"EPJ"},
  {c:"Vêtements de travail",s:"Sweet A Capuche",r:"TEX SWEET A CAPUCHE XL",n:"SWEET A CAPUCHE TAILLE XL",u:"Pièce",stock:true,fournisseur:"EPJ",codeEsabora:"EPJ"},
  {c:"Vêtements de travail",s:"Veste Softshell",r:"TEX VESTE SOFTSHELL M",n:"VESTE SOFTSHELL TAILLE M",u:"Pièce",stock:true,fournisseur:"EPJ",codeEsabora:"EPJ"},
  {c:"Vêtements de travail",s:"Veste Softshell",r:"TEX VESTE SOFTSHELL L",n:"VESTE SOFTSHELL TAILLE L",u:"Pièce",stock:true,fournisseur:"EPJ",codeEsabora:"EPJ"},
  {c:"Vêtements de travail",s:"Veste Softshell",r:"TEX VESTE SOFTSHELL XL",n:"VESTE SOFTSHELL TAILLE XL",u:"Pièce",stock:true,fournisseur:"EPJ",codeEsabora:"EPJ"},
  {c:"Vêtements de travail",s:"Gilet Polaire",r:"TEX GILET POLAIRE S",n:"VESTE SOFTSHELL TAILLE M",u:"Pièce",stock:true,fournisseur:"EPJ",codeEsabora:"EPJ"},
  {c:"Vêtements de travail",s:"Gilet Polaire",r:"TEX GILET POLAIRE M",n:"VESTE SOFTSHELL TAILLE L",u:"Pièce",stock:true,fournisseur:"EPJ",codeEsabora:"EPJ"},
  {c:"Vêtements de travail",s:"Gilet Polaire",r:"TEX GILET POLAIRE  L",n:"VESTE SOFTSHELL TAILLE XL",u:"Pièce",stock:true,fournisseur:"EPJ",codeEsabora:"EPJ"},
  {c:"Vêtements de travail",s:"Bonnet / Casquette",r:"TEX BONNETG",n:"BONNET GRIS",u:"Pièce",stock:true,fournisseur:"EPJ",codeEsabora:"EPJ"},
  {c:"Vêtements de travail",s:"Bonnet / Casquette",r:"TEX BONNET N",n:"BONNET NOIR",u:"Pièce",stock:true,fournisseur:"EPJ",codeEsabora:"EPJ"},
  {c:"Vêtements de travail",s:"Bonnet / Casquette",r:"TEX CASQUETTE",n:"CAQUETTE DE SECURITE",u:"Pièce",stock:true,fournisseur:"EPJ",codeEsabora:"EPJ"},
  {c:"Vêtements de travail",s:"Botte De Securite",r:"VIN 362357",n:"BOTTE SECURITE FOURREES ZEUS T42 K702",u:"Pièce",stock:false,fournisseur:"VINAY",codeEsabora:"VIN"},
  {c:"Vêtements de travail",s:"Botte De Securite",r:"VIN 362358",n:"BOTTE SECURITE FOURREES ZEUS  T43 K702",u:"Pièce",stock:false,fournisseur:"VINAY",codeEsabora:"VIN"},
  {c:"Vêtements de travail",s:"Botte De Securite",r:"VIN 362353",n:"BOTTE SECURITE FOURREES ZEUS  T44 K702",u:"Pièce",stock:false,fournisseur:"VINAY",codeEsabora:"VIN"},
  {c:"Vêtements de travail",s:"Botte De Securite",r:"VIN 362360",n:"BOTTE SECURITE FOURREES ZEUS  T45 K702",u:"Pièce",stock:false,fournisseur:"VINAY",codeEsabora:"VIN"},
  {c:"EPI",s:"Epi",r:"VIN 360351",n:"CASQUE CHANTIER + LUNETTE KARA   BLANC",u:"Pièce",stock:false,fournisseur:"VINAY",codeEsabora:"VIN"},
  {c:"EPI",s:"Epi",r:"VIN 360471",n:"GARNITURE SANI CONTOURE CASQUE KARA",u:"Pièce",stock:true,fournisseur:"VINAY",codeEsabora:"VIN"},
  {c:"EPI",s:"Epi",r:"VIN 361660",n:"GANT CHAUD NOIR SNOWFLEX T9/  T10/T11",u:"Pièce",stock:true,fournisseur:"VINAY",codeEsabora:"VIN"},
  {c:"EPI",s:"Epi",r:"VIN 360027",n:"LUNETTE A BRANCHE VISILUX",u:"Pièce",stock:false,fournisseur:"VINAY",codeEsabora:"VIN"},
  {c:"EPI",s:"Epi",r:"VIN 360332",n:"CASQUE ANTIBRUIT ARCEAU",u:"Pièce",stock:true,fournisseur:"VINAY",codeEsabora:"VIN"},
  {c:"EPI",s:"Epi",r:"VIN 360239",n:"MASQUE PAPIER FFP2 AV VALVE",u:"Pièce",stock:true,fournisseur:"VINAY",codeEsabora:"VIN"},
  {c:"Fils / Câbles",s:"Général",r:"ACO R7295AST",n:"CABLE 4P CAT6A F/FTP LSOH DCA",u:"Pièce",stock:false,fournisseur:"TETRADIS",codeEsabora:"TETR"},
  {c:"Fils / Câbles",s:"Général",r:"ACO R8596AT5",n:"2X4P F/FTP CAT.6A LSOH- CCA-T500",u:"Pièce",stock:false,fournisseur:"TETRADIS",codeEsabora:"TETR"},
  {c:"Fils / Câbles",s:"Général",r:"FIL H07VU1,5VJC100",n:"Fil H07VU 1,5 Vert/Jaune C100M",u:"ML",stock:true,fournisseur:"SONEPAR",codeEsabora:"SONE"},
  {c:"Fils / Câbles",s:"Général",r:"FIL H07VU1,5RGC100",n:"Fil H07VU 1,5 Rouge C100M",u:"ML",stock:true,fournisseur:"SONEPAR",codeEsabora:"SONE"},
  {c:"Fils / Câbles",s:"Général",r:"FIL H07VU1,5BEC100",n:"Fil H07VU 1,5 Bleu C100M",u:"ML",stock:true,fournisseur:"SONEPAR",codeEsabora:"SONE"},
  {c:"Fils / Câbles",s:"Général",r:"FIL H07VU1,5GRC100",n:"Fil H07VU 1,5 Gris C100M",u:"ML",stock:true,fournisseur:"SONEPAR",codeEsabora:"SONE"},
  {c:"Fils / Câbles",s:"Général",r:"FIL H07VU1,5IVC100",n:"Fil H07VU 1,5 Ivoire C100M",u:"ML",stock:true,fournisseur:"SONEPAR",codeEsabora:"SONE"},
  {c:"Fils / Câbles",s:"Général",r:"FIL H07VU1,5NRC100",n:"Fil H07VU 1,5 Noir C100M",u:"ML",stock:true,fournisseur:"SONEPAR",codeEsabora:"SONE"},
  {c:"Fils / Câbles",s:"Général",r:"FIL H07VU1,5ORC100",n:"Fil H07VU 1,5 Orange C100M",u:"ML",stock:true,fournisseur:"SONEPAR",codeEsabora:"SONE"},
  {c:"Fils / Câbles",s:"Général",r:"FIL H07VU1,5MNC100",n:"Fil H07VU 1,5 Marron C100M",u:"ML",stock:true,fournisseur:"SONEPAR",codeEsabora:"SONE"},
  {c:"Fils / Câbles",s:"Général",r:"FIL H07VU1,5VIC100",n:"Fil H07VU 1,5 Violet C100M",u:"ML",stock:true,fournisseur:"SONEPAR",codeEsabora:"SONE"},
  {c:"Fils / Câbles",s:"Général",r:"FIL H07VU2,5VJC100",n:"Fil H07VU 2,5 Vert/Jaune C100M",u:"ML",stock:true,fournisseur:"SONEPAR",codeEsabora:"SONE"},
  {c:"Fils / Câbles",s:"Général",r:"FIL H07VU2,5RGC100",n:"Fil H07VU 2,5 Rouge C100M",u:"ML",stock:true,fournisseur:"SONEPAR",codeEsabora:"SONE"},
  {c:"Fils / Câbles",s:"Général",r:"FIL H07VU2,5BEC100",n:"Fil H07VU 2,5 Bleu C100M",u:"ML",stock:true,fournisseur:"SONEPAR",codeEsabora:"SONE"},
  {c:"Fils / Câbles",s:"Général",r:"FIL H07VU2,5GRC100",n:"Fil H07VU 2,5 Gris C100M",u:"ML",stock:true,fournisseur:"SONEPAR",codeEsabora:"SONE"},
  {c:"Fils / Câbles",s:"Général",r:"FIL H07VU2,5IVC100",n:"Fil H07VU 2,5 Ivoire C100M",u:"ML",stock:false,fournisseur:"SONEPAR",codeEsabora:"SONE"},
  {c:"Fils / Câbles",s:"Général",r:"FIL H07VU2,5NRC100",n:"Fil H07VU 2,5 Noir C100M",u:"ML",stock:true,fournisseur:"SONEPAR",codeEsabora:"SONE"},
  {c:"Fils / Câbles",s:"Général",r:"FIL H07VU2,5ORC100",n:"Fil H07VU 2,5 Orange C100M",u:"ML",stock:true,fournisseur:"SONEPAR",codeEsabora:"SONE"},
  {c:"Fils / Câbles",s:"Général",r:"FIL H07VU2,5MNC100",n:"Fil H07VU 2,5 Marron C100M",u:"ML",stock:false,fournisseur:"SONEPAR",codeEsabora:"SONE"},
  {c:"Fils / Câbles",s:"Général",r:"FIL H07VU2,5VIC100",n:"Fil H07VU 2,5 Violet C100M",u:"ML",stock:false,fournisseur:"SONEPAR",codeEsabora:"SONE"},
  {c:"Fils / Câbles",s:"Général",r:"FIL H07VU2,5BAC100",n:"Fil H07VU 2,5 Blanc C100M",u:"ML",stock:false,fournisseur:"SONEPAR",codeEsabora:"SONE"},
  {c:"Fils / Câbles",s:"Général",r:"FIL H07VR6VJC100",n:"Fil H07VR 6 Vert/Jaune C100M",u:"ML",stock:true,fournisseur:"SONEPAR",codeEsabora:"SONE"},
  {c:"Fils / Câbles",s:"Général",r:"FIL H07VR6RGC100",n:"Fil H07VR 6 Rouge C100M",u:"ML",stock:true,fournisseur:"SONEPAR",codeEsabora:"SONE"},
  {c:"Fils / Câbles",s:"Général",r:"FIL H07VR6BEC100",n:"Fil H07VR 6 Bleu C100M",u:"ML",stock:true,fournisseur:"SONEPAR",codeEsabora:"SONE"},
  {c:"Fils / Câbles",s:"Général",r:"FIL H07VR6NRC100",n:"Fil H07VR 6 Noir C100M",u:"ML",stock:false,fournisseur:"SONEPAR",codeEsabora:"SONE"},
  {c:"Fils / Câbles",s:"Général",r:"FIL H07VR6MNC100",n:"Fil H07VR 6 Marron C100M",u:"ML",stock:false,fournisseur:"SONEPAR",codeEsabora:"SONE"},
  {c:"Fils / Câbles",s:"Général",r:"FIL R2V2X1,5C100",n:"Câble U1000 R2V CU 2X1,5 C100M",u:"ML",stock:false,fournisseur:"SONEPAR",codeEsabora:"SONE"},
  {c:"Fils / Câbles",s:"Général",r:"FIL R2V3G1,5C100",n:"Câble U1000 R2V CU 3G1,5 C100M",u:"ML",stock:true,fournisseur:"SONEPAR",codeEsabora:"SONE"},
  {c:"Fils / Câbles",s:"Général",r:"FIL R2V4G1,5C100",n:"Câble U1000 R2V CU 4G1,5 C100M",u:"ML",stock:false,fournisseur:"SONEPAR",codeEsabora:"SONE"},
  {c:"Fils / Câbles",s:"Général",r:"FIL R2V5G1,5C100",n:"Câble U1000 R2V CU 5G1,5 C100M",u:"ML",stock:true,fournisseur:"SONEPAR",codeEsabora:"SONE"},
  {c:"Fils / Câbles",s:"Général",r:"FIL R2V3G2,5C100",n:"Câble U1000 R2V CU 3G2,5 C100M",u:"ML",stock:true,fournisseur:"SONEPAR",codeEsabora:"SONE"},
  {c:"Fils / Câbles",s:"Général",r:"FIL R2V4G2,5C100",n:"Câble U1000 R2V CU 4G2,5 C100M",u:"ML",stock:false,fournisseur:"SONEPAR",codeEsabora:"SONE"},
  {c:"Fils / Câbles",s:"Général",r:"FIL R2V5G2,5C100",n:"Câble U1000 R2V CU 5G2,5 C100M",u:"ML",stock:true,fournisseur:"SONEPAR",codeEsabora:"SONE"},
  {c:"Fils / Câbles",s:"Général",r:"FIL R2V7G2,5TGL",n:"Câble U1000 R2V CU 7G2,5 TGL",u:"ML",stock:false,fournisseur:"SONEPAR",codeEsabora:"SONE"},
  {c:"Fils / Câbles",s:"Général",r:"FIL R2V3G4TGL",n:"Câble U1000 R2V CU 3G4 TGL",u:"ML",stock:false,fournisseur:"SONEPAR",codeEsabora:"SONE"},
  {c:"Fils / Câbles",s:"Général",r:"FIL R2V4G4TGL",n:"Câble U1000 R2V CU 4G4 TGL",u:"ML",stock:false,fournisseur:"SONEPAR",codeEsabora:"SONE"},
  {c:"Fils / Câbles",s:"Général",r:"FIL R2V5G4TGL",n:"Câble U1000 R2V CU 5G4 TGL",u:"ML",stock:false,fournisseur:"SONEPAR",codeEsabora:"SONE"},
  {c:"Fils / Câbles",s:"Général",r:"FIL R2V3G6TGL",n:"Câble U1000 R2V CU 3G6 TGL",u:"ML",stock:false,fournisseur:"SONEPAR",codeEsabora:"SONE"},
  {c:"Fils / Câbles",s:"Général",r:"FIL R2V5G6TGL",n:"Câble U1000 R2V CU 5G6 TGL",u:"ML",stock:false,fournisseur:"SONEPAR",codeEsabora:"SONE"},
  {c:"Fils / Câbles",s:"Général",r:"FIL R2V3G10TGL",n:"Câble U1000 R2V CU 3G10 TGL",u:"ML",stock:false,fournisseur:"SONEPAR",codeEsabora:"SONE"},
  {c:"Fils / Câbles",s:"Général",r:"FIL R2V4G10TGL",n:"Câble U1000 R2V CU 4G10 TGL",u:"ML",stock:false,fournisseur:"SONEPAR",codeEsabora:"SONE"},
  {c:"Fils / Câbles",s:"Général",r:"FIL R2V4X10TGL",n:"Câble U1000 R2V CU 4X10 SVJ TGL",u:"ML",stock:false,fournisseur:"SONEPAR",codeEsabora:"SONE"},
  {c:"Fils / Câbles",s:"Général",r:"FIL R2V5G10TGL",n:"Câble U1000 R2V CU 5G10 TGL",u:"ML",stock:false,fournisseur:"SONEPAR",codeEsabora:"SONE"},
  {c:"Fils / Câbles",s:"Général",r:"FIL R2V2X16TGL",n:"Câble U1000 R2V CU 2X16 TGL",u:"ML",stock:false,fournisseur:"SONEPAR",codeEsabora:"SONE"},
  {c:"Fils / Câbles",s:"Général",r:"FIL R2V3G16TGL",n:"Câble U1000 R2V CU 3G16 TGL",u:"ML",stock:false,fournisseur:"SONEPAR",codeEsabora:"SONE"},
  {c:"Fils / Câbles",s:"Général",r:"FIL R2V4G16TGL",n:"Câble U1000 R2V CU 4G16 TGL",u:"ML",stock:false,fournisseur:"SONEPAR",codeEsabora:"SONE"},
  {c:"Fils / Câbles",s:"Général",r:"FIL R2V4X16TGL",n:"Câble U1000 R2V CU 4X16 SVJ TGL",u:"ML",stock:false,fournisseur:"SONEPAR",codeEsabora:"SONE"},
  {c:"Fils / Câbles",s:"Général",r:"FIL R2V5G16TGL",n:"Câble U1000 R2V CU 5G16 TGL",u:"ML",stock:false,fournisseur:"SONEPAR",codeEsabora:"SONE"},
  {c:"Fils / Câbles",s:"Général",r:"FIL R2V2X25TGL",n:"Câble U1000 R2V CU 2X25 TGL",u:"ML",stock:false,fournisseur:"SONEPAR",codeEsabora:"SONE"},
  {c:"Fils / Câbles",s:"Général",r:"FIL R2V4G25TGL",n:"Câble U1000 R2V CU 4G25 TGL",u:"ML",stock:false,fournisseur:"SONEPAR",codeEsabora:"SONE"},
  {c:"Fils / Câbles",s:"Général",r:"FIL R2V4X25TGL",n:"Câble U1000 R2V CU 4X25 SVJ TGL",u:"ML",stock:false,fournisseur:"SONEPAR",codeEsabora:"SONE"},
  {c:"Fils / Câbles",s:"Général",r:"FIL R2V5G25TGL",n:"Câble U1000 R2V CU 5G25 TGL",u:"ML",stock:false,fournisseur:"SONEPAR",codeEsabora:"SONE"},
  {c:"Fils / Câbles",s:"Général",r:"FIL R2V2X35TGL",n:"Câble U1000 R2V CU 2X35 TGL",u:"ML",stock:false,fournisseur:"SONEPAR",codeEsabora:"SONE"},
  {c:"Fils / Câbles",s:"Général",r:"FIL R2V4G35TGL",n:"Câble U1000 R2V CU 4G35 TGL",u:"ML",stock:false,fournisseur:"SONEPAR",codeEsabora:"SONE"},
  {c:"Fils / Câbles",s:"Général",r:"FIL R2V4X35TGL",n:"Câble U1000 R2V CU 4X35 SVJ TGL",u:"ML",stock:false,fournisseur:"SONEPAR",codeEsabora:"SONE"},
  {c:"Fils / Câbles",s:"Général",r:"FIL R2V5G35TGL",n:"Câble U1000 R2V CU 5G35 TGL",u:"ML",stock:false,fournisseur:"SONEPAR",codeEsabora:"SONE"},
  {c:"Fils / Câbles",s:"Général",r:"FIL R2V1X50TGL",n:"Câble U1000 R2V CU 1X50 TGL",u:"ML",stock:false,fournisseur:"SONEPAR",codeEsabora:"SONE"},
  {c:"Fils / Câbles",s:"Général",r:"FIL R2V2X50TGL",n:"Câble U1000 R2V CU 2X50 TGL",u:"ML",stock:false,fournisseur:"SONEPAR",codeEsabora:"SONE"},
  {c:"Fils / Câbles",s:"Général",r:"FIL R2V4G50TGL",n:"Câble U1000 R2V CU 4G50 TGL",u:"ML",stock:false,fournisseur:"SONEPAR",codeEsabora:"SONE"},
  {c:"Fils / Câbles",s:"Général",r:"FIL R2V4X50TGL",n:"Câble U1000 R2V CU 4X50 SVJ TGL",u:"ML",stock:false,fournisseur:"SONEPAR",codeEsabora:"SONE"},
  {c:"Fils / Câbles",s:"Général",r:"FIL R2V5G50TGL",n:"Câble U1000 R2V CU 5G50 TGL",u:"ML",stock:false,fournisseur:"SONEPAR",codeEsabora:"SONE"},
];
